/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Object } from '../../models/object';
import { PaginatedRestaurantSummariesResponseDto } from '../../models/paginated-restaurant-summaries-response-dto';

export interface FavoritesControllerGetFavoriteRestaurants$Params {
  page?: Object;
  limit?: Object;
}

export function favoritesControllerGetFavoriteRestaurants(http: HttpClient, rootUrl: string, params?: FavoritesControllerGetFavoriteRestaurants$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedRestaurantSummariesResponseDto>> {
  const rb = new RequestBuilder(rootUrl, favoritesControllerGetFavoriteRestaurants.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedRestaurantSummariesResponseDto>;
    })
  );
}

favoritesControllerGetFavoriteRestaurants.PATH = '/api/v1/favorites/restaurants';
