/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FavoriteToggleResponseDto } from '../../models/favorite-toggle-response-dto';

export interface FavoritesControllerRemoveMenuItemFavorite$Params {
  menuItemId: string;
}

export function favoritesControllerRemoveMenuItemFavorite(http: HttpClient, rootUrl: string, params: FavoritesControllerRemoveMenuItemFavorite$Params, context?: HttpContext): Observable<StrictHttpResponse<FavoriteToggleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, favoritesControllerRemoveMenuItemFavorite.PATH, 'delete');
  if (params) {
    rb.path('menuItemId', params.menuItemId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FavoriteToggleResponseDto>;
    })
  );
}

favoritesControllerRemoveMenuItemFavorite.PATH = '/api/v1/favorites/menu-items/{menuItemId}';
