/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuAddonResponseDto } from '../../models/menu-addon-response-dto';
import { UpdateAddonDto } from '../../models/update-addon-dto';

export interface MenuControllerUpdateAddon$Params {
  id: string;
      body: UpdateAddonDto
}

export function menuControllerUpdateAddon(http: HttpClient, rootUrl: string, params: MenuControllerUpdateAddon$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuAddonResponseDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerUpdateAddon.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuAddonResponseDto>;
    })
  );
}

menuControllerUpdateAddon.PATH = '/api/v1/menu/addons/{id}';
