/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuCategoryResponseDto } from '../../models/menu-category-response-dto';

export interface MenuControllerGetCategoryById$Params {
  id: string;
}

export function menuControllerGetCategoryById(http: HttpClient, rootUrl: string, params: MenuControllerGetCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuCategoryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerGetCategoryById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuCategoryResponseDto>;
    })
  );
}

menuControllerGetCategoryById.PATH = '/api/v1/menu/categories/{id}';
