/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuItemVariantResponseDto } from '../../models/menu-item-variant-response-dto';

export interface MenuControllerGetVariantById$Params {
  id: string;
}

export function menuControllerGetVariantById(http: HttpClient, rootUrl: string, params: MenuControllerGetVariantById$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuItemVariantResponseDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerGetVariantById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuItemVariantResponseDto>;
    })
  );
}

menuControllerGetVariantById.PATH = '/api/v1/menu/variants/{id}';
