/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuCategoryResponseDto } from '../../models/menu-category-response-dto';

export interface MenuControllerGetRestaurantMenu$Params {
  restaurantId: string;
}

export function menuControllerGetRestaurantMenu(http: HttpClient, rootUrl: string, params: MenuControllerGetRestaurantMenu$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MenuCategoryResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, menuControllerGetRestaurantMenu.PATH, 'get');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MenuCategoryResponseDto>>;
    })
  );
}

menuControllerGetRestaurantMenu.PATH = '/api/v1/menu/{restaurantId}';
