/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMenuItemVariantDto } from '../../models/create-menu-item-variant-dto';
import { MenuItemVariantResponseDto } from '../../models/menu-item-variant-response-dto';

export interface MenuControllerCreateVariant$Params {
  id: string;
      body: CreateMenuItemVariantDto
}

export function menuControllerCreateVariant(http: HttpClient, rootUrl: string, params: MenuControllerCreateVariant$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuItemVariantResponseDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerCreateVariant.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuItemVariantResponseDto>;
    })
  );
}

menuControllerCreateVariant.PATH = '/api/v1/menu/items/{id}/variants';
