/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCategoryDto } from '../../models/create-category-dto';
import { MenuCategoryResponseDto } from '../../models/menu-category-response-dto';

export interface MenuControllerCreateCategory$Params {
      body: CreateCategoryDto
}

export function menuControllerCreateCategory(http: HttpClient, rootUrl: string, params: MenuControllerCreateCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuCategoryResponseDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerCreateCategory.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuCategoryResponseDto>;
    })
  );
}

menuControllerCreateCategory.PATH = '/api/v1/menu/categories';
