/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PresenceControllerGetStatus$Params {

/**
 * Delivery partner ID
 */
  partnerId: string;
}

export function presenceControllerGetStatus(http: HttpClient, rootUrl: string, params: PresenceControllerGetStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, presenceControllerGetStatus.PATH, 'get');
  if (params) {
    rb.path('partnerId', params.partnerId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

presenceControllerGetStatus.PATH = '/api/v1/presence/{partnerId}';
