/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedUsersResponseDto } from '../../models/paginated-users-response-dto';

export interface UsersControllerGetAllUsers$Params {
  status?: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'BLOCKED';
  role?: 'CUSTOMER' | 'RESTAURANT_OWNER' | 'RESTAURANT_MANAGER' | 'DELIVERY_PARTNER' | 'SUPPORT_AGENT' | 'ADMIN' | 'SUPER_ADMIN';
  search?: any;
  limit?: number;
  page?: number;
}

export function usersControllerGetAllUsers(http: HttpClient, rootUrl: string, params?: UsersControllerGetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedUsersResponseDto>> {
  const rb = new RequestBuilder(rootUrl, usersControllerGetAllUsers.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('role', params.role, {});
    rb.query('search', params.search, {});
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedUsersResponseDto>;
    })
  );
}

usersControllerGetAllUsers.PATH = '/api/v1/users';
