/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BranchResponseDto } from '../../models/branch-response-dto';
import { CreateBranchDto } from '../../models/create-branch-dto';

export interface BranchesControllerCreate$Params {
  restaurantId: string;
      body: CreateBranchDto
}

export function branchesControllerCreate(http: HttpClient, rootUrl: string, params: BranchesControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<BranchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, branchesControllerCreate.PATH, 'post');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BranchResponseDto>;
    })
  );
}

branchesControllerCreate.PATH = '/api/v1/restaurants/{restaurantId}/branches';
