/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeliveryOnboardingResponseDto } from '../../models/delivery-onboarding-response-dto';

export interface DeliveryOnboardingControllerCompleteStep$Params {

/**
 * 1-12
 */
  step: number;
}

export function deliveryOnboardingControllerCompleteStep(http: HttpClient, rootUrl: string, params: DeliveryOnboardingControllerCompleteStep$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryOnboardingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, deliveryOnboardingControllerCompleteStep.PATH, 'patch');
  if (params) {
    rb.path('step', params.step, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeliveryOnboardingResponseDto>;
    })
  );
}

deliveryOnboardingControllerCompleteStep.PATH = '/api/v1/delivery/onboarding/steps/{step}';
