/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BankAccountResponseDto } from '../../models/bank-account-response-dto';

export interface BankAccountControllerReject$Params {
  restaurantId: string;
}

export function bankAccountControllerReject(http: HttpClient, rootUrl: string, params: BankAccountControllerReject$Params, context?: HttpContext): Observable<StrictHttpResponse<BankAccountResponseDto>> {
  const rb = new RequestBuilder(rootUrl, bankAccountControllerReject.PATH, 'patch');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BankAccountResponseDto>;
    })
  );
}

bankAccountControllerReject.PATH = '/api/v1/restaurants/{restaurantId}/bank-account/reject';
