/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeliveryDocumentResponseDto } from '../../models/delivery-document-response-dto';

export interface AdminDocumentsControllerVerify$Params {
  deliveryPartnerId: string;
  documentId: string;
}

export function adminDocumentsControllerVerify(http: HttpClient, rootUrl: string, params: AdminDocumentsControllerVerify$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryDocumentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, adminDocumentsControllerVerify.PATH, 'patch');
  if (params) {
    rb.path('deliveryPartnerId', params.deliveryPartnerId, {});
    rb.path('documentId', params.documentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeliveryDocumentResponseDto>;
    })
  );
}

adminDocumentsControllerVerify.PATH = '/api/v1/delivery/admin/{deliveryPartnerId}/documents/{documentId}/verify';
