/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerificationResponseDto } from '../../models/verification-response-dto';

export interface VerificationControllerSubmit$Params {
  restaurantId: string;
}

export function verificationControllerSubmit(http: HttpClient, rootUrl: string, params: VerificationControllerSubmit$Params, context?: HttpContext): Observable<StrictHttpResponse<VerificationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, verificationControllerSubmit.PATH, 'post');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerificationResponseDto>;
    })
  );
}

verificationControllerSubmit.PATH = '/api/v1/restaurants/{restaurantId}/verification/submit';
