/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminAdjustWalletDto } from '../../models/admin-adjust-wallet-dto';
import { WalletTransactionResponseDto } from '../../models/wallet-transaction-response-dto';

export interface WalletControllerAdjustBalance$Params {
  userId: string;
      body: AdminAdjustWalletDto
}

export function walletControllerAdjustBalance(http: HttpClient, rootUrl: string, params: WalletControllerAdjustBalance$Params, context?: HttpContext): Observable<StrictHttpResponse<WalletTransactionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, walletControllerAdjustBalance.PATH, 'patch');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WalletTransactionResponseDto>;
    })
  );
}

walletControllerAdjustBalance.PATH = '/api/v1/wallet/admin/{userId}/adjust';
