/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerHomeResponseDto } from '../../models/customer-home-response-dto';

export interface CustomerHomeControllerGetHome$Params {
  lng?: number;
  lat?: number;
}

export function customerHomeControllerGetHome(http: HttpClient, rootUrl: string, params?: CustomerHomeControllerGetHome$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerHomeResponseDto>> {
  const rb = new RequestBuilder(rootUrl, customerHomeControllerGetHome.PATH, 'get');
  if (params) {
    rb.query('lng', params.lng, {});
    rb.query('lat', params.lat, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerHomeResponseDto>;
    })
  );
}

customerHomeControllerGetHome.PATH = '/api/v1/customer/home';
