/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegisterDto } from '../../models/register-dto';
import { RegisterResponseDto } from '../../models/register-response-dto';

export interface AuthControllerRegisterDeliveryPartner$Params {
      body: RegisterDto
}

export function authControllerRegisterDeliveryPartner(http: HttpClient, rootUrl: string, params: AuthControllerRegisterDeliveryPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<RegisterResponseDto>> {
  const rb = new RequestBuilder(rootUrl, authControllerRegisterDeliveryPartner.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegisterResponseDto>;
    })
  );
}

authControllerRegisterDeliveryPartner.PATH = '/api/v1/auth/register/delivery-partner';
