/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeliveryAssignmentResponseDto } from '../../models/delivery-assignment-response-dto';

export interface DispatchControllerGetAssignments$Params {
}

export function dispatchControllerGetAssignments(http: HttpClient, rootUrl: string, params?: DispatchControllerGetAssignments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DeliveryAssignmentResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, dispatchControllerGetAssignments.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DeliveryAssignmentResponseDto>>;
    })
  );
}

dispatchControllerGetAssignments.PATH = '/api/v1/dispatch/assignments';
