/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressResponseDto {
  addressLine1: string;
  addressLine2?: string;
  city: string;
  createdAt: string;
  customLabel?: string;
  customerId: string;
  deliveryInstructions?: string;
  id: string;
  isDefault: boolean;
  label: 'HOME' | 'WORK' | 'OTHER';
  landmark?: string;
  latitude?: number;
  longitude?: number;
  postalCode: string;
  state: string;
  updatedAt: string;
}
