/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressResponseDto {
  accuracy?: number;
  addressLine1: string;
  addressLine2?: string;
  altitude?: number;
  city: string;
  createdAt: string;
  customLabel?: string;
  customerId: string;
  deliveryInstructions?: string;
  heading?: number;
  id: string;
  isDefault: boolean;
  label: 'HOME' | 'WORK' | 'OTHER';
  landmark?: string;
  latitude?: number;
  locationSource?: 'GPS' | 'MANUAL' | 'AUTOCOMPLETE' | 'REVERSE_GEOCODE' | 'MAP_CLICK' | 'MARKER_DRAG';
  longitude?: number;
  postalCode: string;
  provider?: 'GOOGLE_MAPS' | 'MAPBOX' | 'HERE_MAPS' | 'OPENSTREETMAP' | 'AZURE_MAPS';
  providerMetadata?: {
};
  providerPlaceId?: string;
  speed?: number;
  state: string;
  updatedAt: string;
  verified: boolean;
  verifiedAt?: string;
}
