/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminOrderCustomerSummaryDto } from '../models/admin-order-customer-summary-dto';
import { AdminOrderDeliveryPartnerSummaryDto } from '../models/admin-order-delivery-partner-summary-dto';
import { AdminOrderPaymentSummaryDto } from '../models/admin-order-payment-summary-dto';
import { AdminOrderRestaurantSummaryDto } from '../models/admin-order-restaurant-summary-dto';
import { OrderItemResponseDto } from '../models/order-item-response-dto';
import { OrderStatusHistoryResponseDto } from '../models/order-status-history-response-dto';
export interface AdminOrderResponseDto {
  createdAt: string;
  customer: AdminOrderCustomerSummaryDto;
  customerId: string;
  deliveredAt?: string;
  deliveryAddress: string;
  deliveryFee: number;
  deliveryPartner?: AdminOrderDeliveryPartnerSummaryDto;
  deliveryPartnerId?: string;
  id: string;
  items: Array<OrderItemResponseDto>;
  notes?: string;
  orderNumber: string;
  payment?: AdminOrderPaymentSummaryDto;
  paymentStatus: 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED';
  restaurant: AdminOrderRestaurantSummaryDto;
  restaurantId: string;
  status: 'PENDING' | 'CONFIRMED' | 'PREPARING' | 'READY_FOR_PICKUP' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED';
  statusHistory: Array<OrderStatusHistoryResponseDto>;
  subtotalAmount: number;
  taxAmount: number;
  totalAmount: number;
  updatedAt: string;
}
