/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminTicketCustomerDto } from '../models/admin-ticket-customer-dto';
export interface AdminTicketResponseDto {
  assignedAgentId?: string;
  category: 'ORDER_ISSUE' | 'PAYMENT_ISSUE' | 'REFUND_REQUEST' | 'CANCELLATION_REQUEST' | 'ACCOUNT_ISSUE' | 'GENERAL';
  createdAt: string;
  customer: AdminTicketCustomerDto;
  description: string;
  escalatedAt?: string;
  firstResponseAt?: string;
  id: string;
  orderId?: string;
  paymentId?: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  resolvedAt?: string;
  status: 'OPEN' | 'IN_PROGRESS' | 'WAITING_ON_CUSTOMER' | 'RESOLVED' | 'CLOSED';
  subject: string;
  ticketNumber: string;
  updatedAt: string;
}
