/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminOrderPaymentSummaryDto {
  amount: number;
  method?: 'UPI' | 'CARD' | 'NETBANKING' | 'WALLET';
  provider?: 'RAZORPAY' | 'STRIPE';
  status: 'PENDING' | 'SUCCESS' | 'FAILED' | 'REFUNDED';
}
