/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminAlertDto {
  createdAt: string;
  id: string;
  message: string;
  severity: 'INFO' | 'WARNING' | 'CRITICAL';
}
