/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminDeliveryCurrentOrderSummaryDto } from '../models/admin-delivery-current-order-summary-dto';
import { AdminDeliveryPartnerUserSummaryDto } from '../models/admin-delivery-partner-user-summary-dto';
export interface AdminDeliveryPartnerResponseDto {

  /**
   * Total deliveries ever completed.
   */
  completedDeliveries: number;
  createdAt: string;

  /**
   * The partner's current non-terminal order, if any.
   */
  currentOrder?: AdminDeliveryCurrentOrderSummaryDto;

  /**
   * Sum of deliveryFee across today's completed deliveries.
   */
  estimatedFeesToday: number;
  id: string;
  isVerified: boolean;
  licenseNumber?: string;

  /**
   * Live presence from Redis — distinct from `status`, which is the durable DB flag. The two can disagree.
   */
  online: boolean;

  /**
   * Durable operational status, toggled by the partner (available/offline) or an admin (suspend/restore).
   */
  status: 'OFFLINE' | 'AVAILABLE' | 'ON_DELIVERY' | 'SUSPENDED';

  /**
   * Deliveries completed today.
   */
  todaysDeliveries: number;
  updatedAt: string;
  user: AdminDeliveryPartnerUserSummaryDto;
  vehicleNumber: string;
  vehicleType: 'BIKE' | 'SCOOTER' | 'BICYCLE' | 'CAR';
}
