/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminNotificationRecipientSummaryDto {
  email?: string;
  firstName: string;
  id: string;
  lastName?: string;
  phone?: string;
}
