/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminDashboardMetricsDto {

  /**
   * Number of delivery partners currently AVAILABLE or ON_DELIVERY
   */
  activeDeliveryPartners: number;

  /**
   * Number of orders currently in a non-terminal status
   */
  activeOrders: number;

  /**
   * Number of orders delivered today
   */
  completedOrdersToday: number;

  /**
   * Sum of successful payments captured today
   */
  grossRevenueToday: number;

  /**
   * Number of orders placed today
   */
  ordersToday: number;

  /**
   * Number of restaurants awaiting approval
   */
  pendingRestaurantApprovals: number;

  /**
   * Total number of users with the CUSTOMER role
   */
  totalCustomers: number;

  /**
   * Total number of restaurants, regardless of approval status
   */
  totalRestaurants: number;
}
