/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminNotificationRecipientSummaryDto } from '../models/admin-notification-recipient-summary-dto';
export interface AdminNotificationResponseDto {
  attempts: number;
  channel: 'PUSH' | 'EMAIL' | 'SMS' | 'WHATSAPP' | 'IN_APP';
  createdAt: string;
  errorMessage?: string;
  id: string;
  message: string;

  /**
   * State captured at creation time, if any.
   */
  metadata?: {
};
  readAt?: string;
  recipient: AdminNotificationRecipientSummaryDto;
  sentAt?: string;
  status: 'PENDING' | 'SENT' | 'FAILED' | 'READ';

  /**
   * Persisted as `title` — displayed to admins as "Subject".
   */
  title: string;
  type: 'ORDER_PLACED' | 'ORDER_STATUS_CHANGED' | 'DELIVERY_PARTNER_ASSIGNED' | 'OFFER' | 'WALLET_CREDIT' | 'REFERRAL_REWARD' | 'TICKET_STATUS_CHANGED' | 'TICKET_MESSAGE' | 'GENERAL' | 'NEW_ORDER_FOR_RESTAURANT' | 'ORDER_CANCELLED_FOR_RESTAURANT' | 'REFUND_FOR_RESTAURANT' | 'CUSTOMER_MESSAGE_FOR_RESTAURANT' | 'DELIVERY_PARTNER_VERIFICATION_SUBMITTED' | 'DELIVERY_PARTNER_VERIFICATION_APPROVED' | 'DELIVERY_PARTNER_VERIFICATION_REJECTED' | 'DELIVERY_PARTNER_CHANGES_REQUESTED' | 'DELIVERY_PARTNER_DOCUMENT_EXPIRING';
  updatedAt: string;
}
