/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminAuditActorSummaryDto } from '../models/admin-audit-actor-summary-dto';
export interface AdminAuditLogResponseDto {
  action: 'CREATE' | 'UPDATE' | 'DELETE' | 'LOGIN' | 'LOGOUT' | 'STATUS_CHANGE' | 'APPROVE' | 'REJECT';

  /**
   * The user who performed the action. Absent for system-initiated events with no actor.
   */
  actor?: AdminAuditActorSummaryDto;
  createdAt: string;
  entityId?: string;
  entityType: string;
  id: string;

  /**
   * Not currently populated by any caller — always null today.
   */
  ipAddress?: string;

  /**
   * State of the entity after the action, if captured.
   */
  newValues?: {
};

  /**
   * State of the entity before the action, if captured.
   */
  oldValues?: {
};

  /**
   * Not currently populated by any caller — always null today.
   */
  userAgent?: string;
}
