/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminPaymentCustomerSummaryDto } from '../models/admin-payment-customer-summary-dto';
import { AdminPaymentOrderSummaryDto } from '../models/admin-payment-order-summary-dto';
import { AdminPaymentRefundSummaryDto } from '../models/admin-payment-refund-summary-dto';
export interface AdminPaymentResponseDto {
  amount: number;
  attemptNumber: number;
  createdAt: string;
  customer: AdminPaymentCustomerSummaryDto;
  id: string;
  isActive: boolean;
  method?: 'UPI' | 'CARD' | 'NETBANKING' | 'WALLET';
  order: AdminPaymentOrderSummaryDto;
  orderId: string;
  provider: 'RAZORPAY' | 'STRIPE';
  providerOrderId?: string;
  providerPaymentId?: string;
  refunds: Array<AdminPaymentRefundSummaryDto>;
  status: 'PENDING' | 'SUCCESS' | 'FAILED' | 'REFUNDED';
  updatedAt: string;
}
