/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplyWalletToOrderDto {

  /**
   * Amount the customer wants to apply from their wallet. Clamped server-side to the lesser of this value, the order total, and the current wallet balance.
   */
  amount: number;
  orderId: string;
}
