/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignmentBranchSummaryDto } from '../models/assignment-branch-summary-dto';
import { AssignmentOrderItemSummaryDto } from '../models/assignment-order-item-summary-dto';
import { AssignmentRestaurantSummaryDto } from '../models/assignment-restaurant-summary-dto';
import { DeliveryCustomerSummaryDto } from '../models/delivery-customer-summary-dto';
export interface AssignmentOrderSummaryDto {
  branch?: AssignmentBranchSummaryDto;
  customer?: DeliveryCustomerSummaryDto;
  deliveryAddress: string;
  deliveryFee: number;
  id: string;
  items: Array<AssignmentOrderItemSummaryDto>;
  latitude?: number;
  longitude?: number;
  notes?: string;
  orderNumber: string;
  restaurant?: AssignmentRestaurantSummaryDto;
  status: 'PENDING' | 'CONFIRMED' | 'PREPARING' | 'READY_FOR_PICKUP' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED';
  totalAmount: number;
}
