/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignTicketDto {

  /**
   * Agent to assign. Omit to self-assign as the calling agent.
   */
  agentId?: string;
}
