/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AvailablePartnerCurrentAssignmentDto {
  orderId: string;
  orderNumber: string;
  restaurantName: string;
}
