/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BranchResponseDto {
  addressLine1: string;
  addressLine2?: string;
  city: string;
  createdAt: string;
  deliveryRadiusKm?: number;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  id: string;
  isActive: boolean;
  isPrimary: boolean;
  landmark?: string;
  latitude?: number;
  longitude?: number;
  name: string;
  phone?: string;
  postalCode: string;
  restaurantId: string;
  state: string;
  timezone?: string;
  updatedAt: string;
}
