/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CartItemAddonOptionResponseDto } from '../models/cart-item-addon-option-response-dto';
export interface CartItemResponseDto {
  addonOptions: Array<CartItemAddonOptionResponseDto>;
  id: string;
  imageUrl?: string;

  /**
   * False if the menu item has since been marked unavailable
   */
  isAvailable: boolean;

  /**
   * (unitPrice + sum of addon prices) * quantity
   */
  lineTotal: number;
  menuItemId: string;
  name: string;
  quantity: number;
  specialInstructions?: string;

  /**
   * Base unit price of the selected variant, or the item, excluding addons
   */
  unitPrice: number;
  variantId?: string;
  variantName?: string;
}
