/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChangePasswordDto {

  /**
   * The account's current password
   */
  currentPassword: string;

  /**
   * New password — minimum 8 characters, must include an uppercase letter, a lowercase letter, a number, and a symbol.
   */
  newPassword: string;
}
