/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CouponResponseDto {
  active: boolean;
  code: string;
  createdAt: string;
  description?: string;
  endsAt: string;
  id: string;
  maxDiscountAmount?: number;
  minOrderAmount: number;
  name: string;
  restaurantId?: string;
  scope: 'PLATFORM' | 'RESTAURANT';
  startsAt: string;
  totalUsed: number;
  type: 'PERCENTAGE' | 'FLAT' | 'FREE_DELIVERY';
  updatedAt: string;
  usageLimit?: number;
  usagePerUser: number;
  value: number;
}
