/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOfferDto {
  description?: string;

  /**
   * When the offer stops being visible. Omit for no end date.
   */
  endsAt?: string;
  imageUrl?: string;
  isActive?: boolean;

  /**
   * Deep link the banner navigates to when tapped — e.g. a restaurant page.
   */
  linkUrl?: string;
  restaurantId: string;

  /**
   * When the offer becomes visible. Omit for immediately.
   */
  startsAt?: string;
  title: string;
  type?: 'PERCENTAGE_OFF' | 'FLAT_OFF' | 'FREE_DELIVERY' | 'BUY_ONE_GET_ONE' | 'CASHBACK' | 'OTHER';
}
