/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateOrderItemDto {
  addonOptionIds?: Array<string>;
  menuItemId: string;
  quantity: number;
  specialInstructions?: string;
  variantId?: string;
}
