/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAddressDto {

  /**
   * GPS accuracy radius in meters, as reported by the capturing device/provider.
   */
  accuracy?: number;
  addressLine1: string;
  addressLine2?: string;

  /**
   * Meters above sea level, if the provider/device reports it.
   */
  altitude?: number;
  city: string;
  customLabel?: string;
  deliveryInstructions?: string;

  /**
   * Compass heading in degrees (0-360), if available.
   */
  heading?: number;
  isDefault?: boolean;
  label: 'HOME' | 'WORK' | 'OTHER';
  landmark?: string;
  latitude?: number;
  locationSource?: 'GPS' | 'MANUAL' | 'AUTOCOMPLETE' | 'REVERSE_GEOCODE' | 'MAP_CLICK' | 'MARKER_DRAG';
  longitude?: number;
  postalCode: string;
  provider?: 'GOOGLE_MAPS' | 'MAPBOX' | 'HERE_MAPS' | 'OPENSTREETMAP' | 'AZURE_MAPS';

  /**
   * Opaque provider-specific payload (e.g. the raw geocoding result) kept for audit/debugging.
   */
  providerMetadata?: {
};

  /**
   * The map provider's own place identifier, e.g. a Google Place ID.
   */
  providerPlaceId?: string;

  /**
   * Speed in meters/second, if available.
   */
  speed?: number;
  state: string;
}
