/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMenuItemDto {
  basePrice: number;
  categoryId: string;
  description?: string;
  isVegan?: boolean;
  isVegetarian?: boolean;
  name: string;
}
