/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBranchDto {
  addressLine1: string;
  addressLine2?: string;
  city: string;

  /**
   * Simple radius in kilometers — polygon/geofence support is future work.
   */
  deliveryRadiusKm?: number;
  emergencyContactName?: string;
  emergencyContactPhone?: string;

  /**
   * First branch created for a restaurant becomes primary automatically regardless of this flag.
   */
  isPrimary?: boolean;
  landmark?: string;
  latitude?: number;
  longitude?: number;
  name: string;
  phone?: string;
  postalCode: string;
  state: string;
  timezone?: string;
}
