/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeliveryPartnerResponseDto {
  createdAt: string;
  currentLatitude?: number;
  currentLongitude?: number;
  id: string;
  isVerified: boolean;
  licenseNumber?: string;
  status: 'OFFLINE' | 'AVAILABLE' | 'ON_DELIVERY' | 'SUSPENDED';
  updatedAt: string;
  userId: string;
  vehicleNumber: string;
  vehicleType: 'BIKE' | 'SCOOTER' | 'BICYCLE' | 'CAR';
}
