/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssignmentOrderSummaryDto } from '../models/assignment-order-summary-dto';
export interface DeliveryAssignmentResponseDto {
  assignedAt: string;
  createdAt: string;
  deliveryPartnerId: string;
  expiresAt?: string;
  id: string;
  order?: AssignmentOrderSummaryDto;
  orderId: string;
  respondedAt?: string;
  status: 'PENDING' | 'ASSIGNED' | 'ACCEPTED' | 'REJECTED' | 'EXPIRED';
  updatedAt: string;
}
