/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeliveryDocumentResponseDto {
  createdAt: string;
  deliveryPartnerId: string;
  documentNumber?: string;
  documentType: 'DRIVING_LICENSE' | 'AADHAAR' | 'PAN' | 'VEHICLE_RC' | 'VEHICLE_INSURANCE' | 'VEHICLE_FITNESS' | 'VEHICLE_POLLUTION' | 'PROFILE_PHOTO' | 'SELFIE' | 'BACKGROUND_VERIFICATION' | 'VEHICLE_PHOTO' | 'OTHER';
  expiryDate?: string;
  fileName: string;
  id: string;
  isLatest: boolean;
  issueDate?: string;
  mimeType: string;
  previousVersionId?: string;
  rejectedReason?: string;
  sizeBytes: number;
  status: 'PENDING' | 'UNDER_REVIEW' | 'VERIFIED' | 'REJECTED' | 'EXPIRED';
  storageUrl: string;
  updatedAt: string;
  uploadedById: string;
  vehicleId?: string;
  verifiedAt?: string;
  verifiedById?: string;
  version: number;
}
