/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpiringDeliveryDocumentDto {
  documentId: string;
  documentType: 'DRIVING_LICENSE' | 'AADHAAR' | 'PAN' | 'VEHICLE_RC' | 'VEHICLE_INSURANCE' | 'VEHICLE_FITNESS' | 'VEHICLE_POLLUTION' | 'PROFILE_PHOTO' | 'SELFIE' | 'BACKGROUND_VERIFICATION' | 'VEHICLE_PHOTO' | 'OTHER';
  expiryDate: string;
}
