/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpiringDocumentDto {
  documentId: string;
  documentType: 'GST' | 'FSSAI' | 'PAN' | 'TRADE_LICENSE' | 'FIRE_NOC' | 'SHOP_ESTABLISHMENT' | 'LIQUOR_LICENSE' | 'HALAL' | 'CANCELLED_CHEQUE' | 'PASSBOOK' | 'AADHAAR' | 'PAN_CARD' | 'RENTAL_AGREEMENT' | 'UTILITY_BILL' | 'OTHER';
  expiryDate: string;
}
