/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InviteStaffDto {

  /**
   * Scopes the invite to one branch — leave empty for restaurant-wide roles like OWNER/CO_OWNER/FINANCE_MANAGER.
   */
  branchId?: string;

  /**
   * Must already be a registered Patheya Express user.
   */
  email: string;
  role: 'OWNER' | 'CO_OWNER' | 'BRANCH_MANAGER' | 'KITCHEN_MANAGER' | 'FINANCE_MANAGER' | 'STAFF';
}
