/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MenuItemVariantResponseDto {
  id: string;
  isDefault: boolean;
  menuItemId: string;
  name: string;
  price: number;
}
