/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuAddonResponseDto } from '../models/menu-addon-response-dto';
import { MenuItemVariantResponseDto } from '../models/menu-item-variant-response-dto';
export interface MenuItemResponseDto {
  addons: Array<MenuAddonResponseDto>;
  basePrice: number;
  categoryId: string;
  description?: string;
  id: string;
  imageUrl?: string;
  isAvailable: boolean;
  isVegan: boolean;
  isVegetarian: boolean;
  name: string;

  /**
   * Populated when the item is returned outside its own category listing (e.g. favorites).
   */
  restaurantId?: string;

  /**
   * Populated when the item is returned outside its own category listing (e.g. favorites).
   */
  restaurantName?: string;
  variants: Array<MenuItemVariantResponseDto>;
}
