/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuAddonOptionResponseDto } from '../models/menu-addon-option-response-dto';
export interface MenuAddonResponseDto {
  id: string;
  maxSelection: number;
  menuItemId: string;
  minSelection: number;
  name: string;
  options: Array<MenuAddonOptionResponseDto>;
}
