/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationPreferencesResponseDto {

  /**
   * Order status update emails
   */
  orderUpdatesEmail: boolean;

  /**
   * Order status update push notifications
   */
  orderUpdatesPush: boolean;

  /**
   * Order status update SMS
   */
  orderUpdatesSms: boolean;

  /**
   * Promotional emails
   */
  promotionsEmail: boolean;

  /**
   * Promotional push notifications
   */
  promotionsPush: boolean;

  /**
   * Promotional SMS
   */
  promotionsSms: boolean;

  /**
   * Review-related emails
   */
  reviewsEmail: boolean;

  /**
   * Review-related push notifications
   */
  reviewsPush: boolean;

  /**
   * Review-related SMS
   */
  reviewsSms: boolean;

  /**
   * System/account emails
   */
  systemEmail: boolean;

  /**
   * System/account push notifications
   */
  systemPush: boolean;

  /**
   * System/account SMS
   */
  systemSms: boolean;
}
