/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferResponseDto {
  description?: string;

  /**
   * When set, the offer stops being returned by any customer-facing endpoint after this time.
   */
  endsAt?: string;
  id: string;
  imageUrl?: string;

  /**
   * Whether the offer is currently enabled. Every offer returned by a customer-facing endpoint is always true here — this only varies on the restaurant-owner management endpoints (GET /offers/manage/:restaurantId), which also return disabled offers.
   */
  isActive: boolean;

  /**
   * Deep link the banner navigates to when tapped — e.g. a restaurant page.
   */
  linkUrl?: string;

  /**
   * Present when the offer is scoped to a specific restaurant rather than platform-wide.
   */
  restaurantId?: string;
  restaurantName?: string;
  startsAt?: string;
  title: string;
  type?: 'PERCENTAGE_OFF' | 'FLAT_OFF' | 'FREE_DELIVERY' | 'BUY_ONE_GET_ONE' | 'CASHBACK' | 'OTHER';
}
