/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrderCustomerSummaryResponseDto } from '../models/order-customer-summary-response-dto';
import { OrderDeliveryPartnerSummaryDto } from '../models/order-delivery-partner-summary-dto';
import { OrderItemResponseDto } from '../models/order-item-response-dto';
import { OrderStatusHistoryResponseDto } from '../models/order-status-history-response-dto';
export interface OrderResponseDto {
  addressId?: string;
  createdAt: string;
  customer?: OrderCustomerSummaryResponseDto;
  customerId: string;
  deliveredAt?: string;
  deliveryAddress: string;
  deliveryFee: number;

  /**
   * Only populated once a delivery partner is assigned, by endpoints that join it (e.g. order detail)
   */
  deliveryPartner?: OrderDeliveryPartnerSummaryDto;
  deliveryPartnerId?: string;
  id: string;
  items: Array<OrderItemResponseDto>;

  /**
   * Delivery destination latitude, resolved from the saved address at order placement
   */
  latitude?: number;

  /**
   * Delivery destination longitude, resolved from the saved address at order placement
   */
  longitude?: number;
  notes?: string;
  orderNumber: string;
  paymentMode: 'ONLINE' | 'COD';
  paymentStatus: 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED';
  restaurantId: string;

  /**
   * Only populated by endpoints that already join the restaurant (e.g. order history)
   */
  restaurantName?: string;
  status: 'PENDING' | 'CONFIRMED' | 'PREPARING' | 'READY_FOR_PICKUP' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED';
  statusHistory: Array<OrderStatusHistoryResponseDto>;
  subtotalAmount: number;
  taxAmount: number;
  totalAmount: number;
}
