/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderLocationResponseDto {

  /**
   * Straight-line distance to the order's delivery destination, in kilometers
   */
  distanceKm?: number;

  /**
   * Estimated minutes until arrival, based on straight-line distance and an assumed average delivery speed
   */
  etaMinutes?: number;
  latitude: number;
  longitude: number;
  updatedAt: string;
}
