/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderItemAddonOptionResponseDto {

  /**
   * The current menu addon option this selection was made from — used to reconstruct a cart line when reordering.
   */
  addonOptionId: string;
  name: string;
  price: number;
}
