/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderItemResponseDto {
  id: string;
  menuItemId: string;
  menuItemName?: string;
  quantity: number;
  specialInstructions?: string;
  totalPrice: number;
  unitPrice: number;
}
