/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OfferResponseDto } from '../models/offer-response-dto';
export interface PaginatedOffersResponseDto {
  items: Array<OfferResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
