/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuItemResponseDto } from '../models/menu-item-response-dto';
export interface PaginatedFavoriteMenuItemsResponseDto {
  items: Array<MenuItemResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
