/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminWalletTransactionResponseDto } from '../models/admin-wallet-transaction-response-dto';
export interface PaginatedAdminWalletTransactionsResponseDto {
  items: Array<AdminWalletTransactionResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
