/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminPaymentResponseDto } from '../models/admin-payment-response-dto';
export interface PaginatedAdminPaymentsResponseDto {
  items: Array<AdminPaymentResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
