/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WalletTransactionResponseDto } from '../models/wallet-transaction-response-dto';
export interface PaginatedWalletTransactionsResponseDto {
  items: Array<WalletTransactionResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
