/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminDeliveryPartnerResponseDto } from '../models/admin-delivery-partner-response-dto';
export interface PaginatedAdminDeliveryPartnersResponseDto {
  items: Array<AdminDeliveryPartnerResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
