/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationResponseDto } from '../models/notification-response-dto';
export interface PaginatedNotificationsResponseDto {
  items: Array<NotificationResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
