/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminOrderResponseDto } from '../models/admin-order-response-dto';
export interface PaginatedAdminOrdersResponseDto {
  items: Array<AdminOrderResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
