/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CouponResponseDto } from '../models/coupon-response-dto';
export interface PaginatedCouponsResponseDto {
  items: Array<CouponResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
