/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuItemSearchResultDto } from '../models/menu-item-search-result-dto';
export interface PaginatedMenuItemSearchResponseDto {
  items: Array<MenuItemSearchResultDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
