/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminAuditLogResponseDto } from '../models/admin-audit-log-response-dto';
export interface PaginatedAdminAuditLogsResponseDto {
  items: Array<AdminAuditLogResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
