/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminNotificationResponseDto } from '../models/admin-notification-response-dto';
export interface PaginatedAdminNotificationsResponseDto {
  items: Array<AdminNotificationResponseDto>;
  limit: number;
  page: number;
  total: number;
  totalPages: number;
}
