/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentResponseDto {
  amount: number;
  attemptNumber: number;
  createdAt: string;
  id: string;
  isActive: boolean;
  method?: 'UPI' | 'CARD' | 'NETBANKING' | 'WALLET' | 'COD';
  orderId: string;
  provider: 'RAZORPAY' | 'STRIPE';
  providerOrderId?: string;
  providerPaymentId?: string;
  status: 'PENDING' | 'SUCCESS' | 'FAILED' | 'REFUNDED';
  updatedAt: string;
}
