/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProofPhotoResponseDto {
  createdAt: string;
  fileName: string;
  id: string;
  mimeType: string;
  orderId: string;
  sizeBytes: number;
  storageUrl: string;
  type: 'PICKUP' | 'DELIVERY';
  uploadedById: string;
}
