/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RatingBreakdownEntryDto } from '../models/rating-breakdown-entry-dto';
export interface RatingSummaryResponseDto {
  averageRating: number;

  /**
   * One entry per star rating 1-5, in descending order, count 0 if none.
   */
  breakdown: Array<RatingBreakdownEntryDto>;
  totalReviews: number;
}
