/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecentOrderSummaryDto {
  createdAt: string;
  customerName: string;
  id: string;
  orderNumber: string;
  status: string;
  totalAmount: number;
}
