/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RefundOrderDto {

  /**
   * Amount to refund. Defaults to the full payment amount when omitted.
   */
  amount?: number;
  reason?: string;
}
