/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthUserDto } from '../models/auth-user-dto';
export interface RegisterResponseDto {
  accessToken: string;
  refreshToken: string;
  user: AuthUserDto;
}
