/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReorderMediaDto {

  /**
   * Media ids in the desired display order — sortOrder is assigned from array position.
   */
  mediaIds: Array<string>;
}
