/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpsertOperatingHourDto } from '../models/upsert-operating-hour-dto';
export interface ReplaceOperatingHoursDto {

  /**
   * The full weekly schedule for this branch — replaces every existing entry. Include multiple entries with the same dayOfWeek for split shifts (e.g. lunch + dinner), or a single isClosed entry for a day the branch does not operate.
   */
  hours: Array<UpsertOperatingHourDto>;
}
