/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OnboardingChangeItemDto } from '../models/onboarding-change-item-dto';
export interface RequestOnboardingChangesDto {
  items: Array<OnboardingChangeItemDto>;
}
