/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeliveryOnboardingChangeItemDto } from '../models/delivery-onboarding-change-item-dto';
export interface RequestDeliveryOnboardingChangesDto {
  items: Array<DeliveryOnboardingChangeItemDto>;
}
