/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OperatingHourResponseDto } from '../models/operating-hour-response-dto';
export interface RestaurantBranchSummaryDto {
  addressLine1?: string;
  addressLine2?: string;
  city: string;
  id?: string;
  latitude?: number;
  longitude?: number;
  name?: string;
  operatingHours?: Array<OperatingHourResponseDto>;
  phone?: string;
  postalCode?: string;
  state?: string;
}
