/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OfferResponseDto } from '../models/offer-response-dto';
import { RestaurantBranchSummaryDto } from '../models/restaurant-branch-summary-dto';
import { RestaurantCuisineSummaryDto } from '../models/restaurant-cuisine-summary-dto';
import { RestaurantOwnerDto } from '../models/restaurant-owner-dto';
export interface RestaurantResponseDto {
  avgRating: number;
  bannerUrl?: string;
  branches?: Array<RestaurantBranchSummaryDto>;
  createdAt: string;
  cuisines?: Array<RestaurantCuisineSummaryDto>;
  description?: string;
  email?: string;
  id: string;
  isActive: boolean;
  logoUrl?: string;
  name: string;
  offers?: Array<OfferResponseDto>;

  /**
   * Only populated by admin-facing endpoints.
   */
  owner?: RestaurantOwnerDto;
  ownerId: string;
  phone?: string;
  ratingCount: number;
  slug: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
  updatedAt: string;
}
