/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RestaurantSummaryDto {
  avgDeliveryTimeMinutes?: number;
  avgPreparationTimeMinutes?: number;
  avgRating: number;
  bannerUrl?: string;
  city?: string;
  cuisines: Array<string>;

  /**
   * Distance from the requested lat/lng, in kilometers. Only present when the request included coordinates.
   */
  distanceKm?: number;
  featured: boolean;

  /**
   * Derived from this restaurant's menu — true if at least one item is marked vegetarian.
   */
  hasVegOptions: boolean;

  /**
   * Derived from this restaurant's menu — true if at least one item is marked vegan.
   */
  hasVeganOptions: boolean;
  id: string;
  isOpenNow: boolean;
  logoUrl?: string;
  name: string;
  ratingCount: number;
  slug: string;
}
