/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PeakHourDto } from '../models/peak-hour-dto';
import { RecentOrderSummaryDto } from '../models/recent-order-summary-dto';
import { TopSellingItemDto } from '../models/top-selling-item-dto';
export interface RestaurantDashboardResponseDto {

  /**
   * accepted / (accepted + rejected) * 100, 0 when nothing has been decided yet.
   */
  acceptanceRate: number;

  /**
   * Orders that reached at least CONFIRMED today.
   */
  accepted: number;

  /**
   * Average minutes from placement to READY_FOR_PICKUP, for today's orders that reached it. Null if none did.
   */
  averagePreparationTimeMinutes?: number;

  /**
   * rejected / ordersToday * 100.
   */
  cancellationRate: number;

  /**
   * Orders placed today that reached DELIVERED.
   */
  completed: number;
  ordersToday: number;

  /**
   * Rolling 30-day window, hours with at least one order only.
   */
  peakHours: Array<PeakHourDto>;
  preparing: number;
  ready: number;
  recentOrders: Array<RecentOrderSummaryDto>;

  /**
   * Orders placed today that ended up CANCELLED.
   */
  rejected: number;

  /**
   * Sum of totalAmount for orders placed in the trailing 30-day window (not calendar-month-to-date).
   */
  revenueThisMonth: number;

  /**
   * Sum of totalAmount for orders placed in the trailing 7 days.
   */
  revenueThisWeek: number;
  revenueToday: number;

  /**
   * Rolling 30-day window.
   */
  topSellingItems: Array<TopSellingItemDto>;
}
