/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewResponseDto {
  comment?: string;
  createdAt: string;
  customerId: string;

  /**
   * The reviewing customer's display name
   */
  customerName?: string;
  id: string;
  rating: number;
  replyCreatedAt?: string;

  /**
   * The restaurant owner/manager reply, if one has been posted.
   */
  replyText?: string;
  replyUpdatedAt?: string;
  restaurantId: string;
  updatedAt: string;
}
