/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SubmitDeliveryOnboardingDto {

  /**
   * Must be true — the wizard cannot be submitted without accepting terms.
   */
  acceptedTerms: boolean;
}
