/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAddressDto {

  /**
   * GPS accuracy radius in meters.
   */
  accuracy?: number;
  addressLine1?: string;
  addressLine2?: string;
  altitude?: number;
  city?: string;
  customLabel?: string;
  deliveryInstructions?: string;
  heading?: number;
  isDefault?: boolean;
  label?: 'HOME' | 'WORK' | 'OTHER';
  landmark?: string;
  latitude?: number;
  locationSource?: 'GPS' | 'MANUAL' | 'AUTOCOMPLETE' | 'REVERSE_GEOCODE' | 'MAP_CLICK' | 'MARKER_DRAG';
  longitude?: number;
  postalCode?: string;
  provider?: 'GOOGLE_MAPS' | 'MAPBOX' | 'HERE_MAPS' | 'OPENSTREETMAP' | 'AZURE_MAPS';
  providerMetadata?: {
};
  providerPlaceId?: string;
  speed?: number;
  state?: string;
}
