/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDeliveryProfileDto {
  currentAddressLatitude?: number;
  currentAddressLine1?: string;
  currentAddressLine2?: string;
  currentAddressLongitude?: number;
  currentCity?: string;
  currentPostalCode?: string;
  currentState?: string;
  dateOfBirth?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  emergencyContactRelation?: string;
  gender?: 'MALE' | 'FEMALE' | 'OTHER' | 'PREFER_NOT_TO_SAY';
  languagesSpoken?: Array<string>;
  permanentAddressLine1?: string;
  permanentAddressLine2?: string;
  permanentCity?: string;
  permanentLatitude?: number;
  permanentLongitude?: number;
  permanentPostalCode?: string;
  permanentState?: string;
  sameAsPermanentAddress?: boolean;
}
