/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfileDto {

  /**
   * User first name
   */
  firstName?: string;

  /**
   * User last name
   */
  lastName?: string;
}
