/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAddressDto {
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  customLabel?: string;
  deliveryInstructions?: string;
  isDefault?: boolean;
  label?: 'HOME' | 'WORK' | 'OTHER';
  landmark?: string;
  latitude?: number;
  longitude?: number;
  postalCode?: string;
  state?: string;
}
