/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfileDto {

  /**
   * User first name
   */
  firstName?: string;

  /**
   * User last name
   */
  lastName?: string;

  /**
   * Whether the user has opted in to marketing communications
   */
  marketingOptIn?: boolean;

  /**
   * User phone number
   */
  phone?: string;

  /**
   * Preferred language (ISO 639-1 code)
   */
  preferredLanguage?: string;
  themePreference?: 'LIGHT' | 'DARK' | 'SYSTEM';

  /**
   * IANA timezone identifier
   */
  timezone?: string;
}
