/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateVehicleDto {
  brand?: string;
  color?: string;
  fuelType?: 'PETROL' | 'DIESEL' | 'ELECTRIC' | 'CNG' | 'HYBRID';
  model?: string;
  registrationNumber?: string;
  year?: number;
}
