/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpsertTaxProfileDto {
  businessType?: 'PROPRIETORSHIP' | 'PARTNERSHIP' | 'LLP' | 'PRIVATE_LIMITED' | 'PUBLIC_LIMITED' | 'TRUST' | 'SOCIETY' | 'OTHER';

  /**
   * Corporate Identification Number, for registered companies.
   */
  cin?: string;
  fssaiExpiryAt?: string;
  fssaiIssueDate?: string;
  fssaiLicenseType?: string;
  fssaiNumber?: string;
  gstBusinessCategory?: string;
  gstLegalName?: string;
  gstRegisteredAddress?: string;
  gstRegistrationState?: string;
  gstin?: string;
  pan?: string;
}
