/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponseDto {
  avatarUrl?: string;
  createdAt: string;
  email?: string;
  firstName: string;
  id: string;
  lastName?: string;
  marketingOptIn: boolean;
  phone?: string;
  preferredLanguage: string;

  /**
   * Percentage (0-100) of optional profile fields that have been filled in. Only populated on "my own profile" responses (GET/PATCH/avatar upload on /users/me), omitted on admin listing endpoints.
   */
  profileCompletion?: number;
  provider: 'EMAIL' | 'GOOGLE' | 'APPLE' | 'PHONE';
  role: 'CUSTOMER' | 'RESTAURANT_OWNER' | 'RESTAURANT_MANAGER' | 'DELIVERY_PARTNER' | 'SUPPORT_AGENT' | 'ADMIN' | 'SUPER_ADMIN' | 'DISPATCH_MANAGER';
  status: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED' | 'BLOCKED';
  themePreference: 'LIGHT' | 'DARK' | 'SYSTEM';
  timezone: string;
  updatedAt: string;
}
