/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ValidateCouponDto {
  code: string;

  /**
   * The restaurant the customer's cart belongs to.
   */
  restaurantId: string;

  /**
   * The cart's current subtotal, used for minOrderAmount and discount calculation.
   */
  subtotal: number;
}
