/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffResponseDto } from '../../models/staff-response-dto';
import { UpdateStaffDto } from '../../models/update-staff-dto';

export interface StaffControllerUpdate$Params {
  restaurantId: string;
  staffId: string;
      body: UpdateStaffDto
}

export function staffControllerUpdate(http: HttpClient, rootUrl: string, params: StaffControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffResponseDto>> {
  const rb = new RequestBuilder(rootUrl, staffControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.path('staffId', params.staffId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffResponseDto>;
    })
  );
}

staffControllerUpdate.PATH = '/api/v1/restaurants/{restaurantId}/staff/{staffId}';
