/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeliveryDocumentResponseDto } from '../../models/delivery-document-response-dto';

export interface DeliveryDocumentsControllerUpload$Params {
      body: {
'file'?: Blob;
'documentType'?: string;
'documentNumber'?: string;
'issueDate'?: string;
'expiryDate'?: string;
'vehicleId'?: string;
'previousVersionId'?: string;
}
}

export function deliveryDocumentsControllerUpload(http: HttpClient, rootUrl: string, params: DeliveryDocumentsControllerUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryDocumentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, deliveryDocumentsControllerUpload.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeliveryDocumentResponseDto>;
    })
  );
}

deliveryDocumentsControllerUpload.PATH = '/api/v1/delivery/documents';
