/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedOffersResponseDto } from '../../models/paginated-offers-response-dto';

export interface OffersControllerFindByRestaurant$Params {
  restaurantId: string;
  page?: number;
  limit?: number;

/**
 * Matches against title/description
 */
  search?: string;
  type?: 'PERCENTAGE_OFF' | 'FLAT_OFF' | 'FREE_DELIVERY' | 'BUY_ONE_GET_ONE' | 'CASHBACK' | 'OTHER';
}

export function offersControllerFindByRestaurant(http: HttpClient, rootUrl: string, params: OffersControllerFindByRestaurant$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedOffersResponseDto>> {
  const rb = new RequestBuilder(rootUrl, offersControllerFindByRestaurant.PATH, 'get');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedOffersResponseDto>;
    })
  );
}

offersControllerFindByRestaurant.PATH = '/api/v1/offers/restaurants/{restaurantId}';
