/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedOffersResponseDto } from '../../models/paginated-offers-response-dto';

export interface OffersControllerFindAllForRestaurant$Params {
  restaurantId: string;
  page?: number;
  limit?: number;

/**
 * Filter to only enabled or only disabled offers. Omit for both.
 */
  isActive?: boolean;
}

export function offersControllerFindAllForRestaurant(http: HttpClient, rootUrl: string, params: OffersControllerFindAllForRestaurant$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedOffersResponseDto>> {
  const rb = new RequestBuilder(rootUrl, offersControllerFindAllForRestaurant.PATH, 'get');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('isActive', params.isActive, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedOffersResponseDto>;
    })
  );
}

offersControllerFindAllForRestaurant.PATH = '/api/v1/offers/manage/{restaurantId}';
