/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResponseDto } from '../../models/document-response-dto';

export interface DocumentsControllerVerify$Params {
  restaurantId: string;
  documentId: string;
}

export function documentsControllerVerify(http: HttpClient, rootUrl: string, params: DocumentsControllerVerify$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, documentsControllerVerify.PATH, 'patch');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.path('documentId', params.documentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponseDto>;
    })
  );
}

documentsControllerVerify.PATH = '/api/v1/restaurants/{restaurantId}/documents/{documentId}/verify';
