/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DocumentResponseDto } from '../../models/document-response-dto';

export interface DocumentsControllerUpload$Params {
  restaurantId: string;
      body: {
'file'?: Blob;
'documentType'?: string;
'documentNumber'?: string;
'issueDate'?: string;
'expiryDate'?: string;
'branchId'?: string;
'previousVersionId'?: string;
}
}

export function documentsControllerUpload(http: HttpClient, rootUrl: string, params: DocumentsControllerUpload$Params, context?: HttpContext): Observable<StrictHttpResponse<DocumentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, documentsControllerUpload.PATH, 'post');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DocumentResponseDto>;
    })
  );
}

documentsControllerUpload.PATH = '/api/v1/restaurants/{restaurantId}/documents';
