/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignOrderToPartnerDto } from '../../models/assign-order-to-partner-dto';
import { DeliveryAssignmentResponseDto } from '../../models/delivery-assignment-response-dto';

export interface AdminDispatchControllerAssignOrderToPartner$Params {
  orderId: string;
      body: AssignOrderToPartnerDto
}

export function adminDispatchControllerAssignOrderToPartner(http: HttpClient, rootUrl: string, params: AdminDispatchControllerAssignOrderToPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryAssignmentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, adminDispatchControllerAssignOrderToPartner.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeliveryAssignmentResponseDto>;
    })
  );
}

adminDispatchControllerAssignOrderToPartner.PATH = '/api/v1/admin/orders/{orderId}/assign';
