/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HolidayResponseDto } from '../../models/holiday-response-dto';
import { UpdateHolidayDto } from '../../models/update-holiday-dto';

export interface HolidaysControllerUpdate$Params {
  restaurantId: string;
  holidayId: string;
      body: UpdateHolidayDto
}

export function holidaysControllerUpdate(http: HttpClient, rootUrl: string, params: HolidaysControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<HolidayResponseDto>> {
  const rb = new RequestBuilder(rootUrl, holidaysControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.path('holidayId', params.holidayId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HolidayResponseDto>;
    })
  );
}

holidaysControllerUpdate.PATH = '/api/v1/restaurants/{restaurantId}/holidays/{holidayId}';
