/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HolidayResponseDto } from '../../models/holiday-response-dto';

export interface HolidaysControllerFindAll$Params {
  restaurantId: string;
  branchId?: string;
}

export function holidaysControllerFindAll(http: HttpClient, rootUrl: string, params: HolidaysControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HolidayResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, holidaysControllerFindAll.PATH, 'get');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.query('branchId', params.branchId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HolidayResponseDto>>;
    })
  );
}

holidaysControllerFindAll.PATH = '/api/v1/restaurants/{restaurantId}/holidays';
