/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderResponseDto } from '../../models/order-response-dto';
import { UpdateDeliveryStatusDto } from '../../models/update-delivery-status-dto';

export interface DeliveryControllerUpdateDeliveryStatus$Params {

/**
 * Order ID
 */
  orderId: string;
      body: UpdateDeliveryStatusDto
}

export function deliveryControllerUpdateDeliveryStatus(http: HttpClient, rootUrl: string, params: DeliveryControllerUpdateDeliveryStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderResponseDto>> {
  const rb = new RequestBuilder(rootUrl, deliveryControllerUpdateDeliveryStatus.PATH, 'patch');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderResponseDto>;
    })
  );
}

deliveryControllerUpdateDeliveryStatus.PATH = '/api/v1/delivery/orders/{orderId}/status';
