/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeliveryBankAccountResponseDto } from '../../models/delivery-bank-account-response-dto';

export interface DeliveryBankAccountControllerFind$Params {
}

export function deliveryBankAccountControllerFind(http: HttpClient, rootUrl: string, params?: DeliveryBankAccountControllerFind$Params, context?: HttpContext): Observable<StrictHttpResponse<DeliveryBankAccountResponseDto>> {
  const rb = new RequestBuilder(rootUrl, deliveryBankAccountControllerFind.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeliveryBankAccountResponseDto>;
    })
  );
}

deliveryBankAccountControllerFind.PATH = '/api/v1/delivery/bank-account';
