/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CouponResponseDto } from '../../models/coupon-response-dto';
import { CreateCouponDto } from '../../models/create-coupon-dto';

export interface CouponsControllerCreate$Params {
      body: CreateCouponDto
}

export function couponsControllerCreate(http: HttpClient, rootUrl: string, params: CouponsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CouponResponseDto>> {
  const rb = new RequestBuilder(rootUrl, couponsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CouponResponseDto>;
    })
  );
}

couponsControllerCreate.PATH = '/api/v1/coupons';
