/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CouponValidationResponseDto } from '../../models/coupon-validation-response-dto';
import { ValidateCouponDto } from '../../models/validate-coupon-dto';

export interface CouponsControllerValidate$Params {
      body: ValidateCouponDto
}

export function couponsControllerValidate(http: HttpClient, rootUrl: string, params: CouponsControllerValidate$Params, context?: HttpContext): Observable<StrictHttpResponse<CouponValidationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, couponsControllerValidate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CouponValidationResponseDto>;
    })
  );
}

couponsControllerValidate.PATH = '/api/v1/coupons/validate';
