/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderResponseDto } from '../../models/order-response-dto';
import { UpdateOrderStatusDto } from '../../models/update-order-status-dto';

export interface OrdersControllerUpdateOrderStatus$Params {
  orderId: string;
      body: UpdateOrderStatusDto
}

export function ordersControllerUpdateOrderStatus(http: HttpClient, rootUrl: string, params: OrdersControllerUpdateOrderStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ordersControllerUpdateOrderStatus.PATH, 'patch');
  if (params) {
    rb.path('orderId', params.orderId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderResponseDto>;
    })
  );
}

ordersControllerUpdateOrderStatus.PATH = '/api/v1/orders/{orderId}/status';
