/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderResponseDto } from '../../models/order-response-dto';

export interface OrdersControllerGetCustomerOrders$Params {
}

export function ordersControllerGetCustomerOrders(http: HttpClient, rootUrl: string, params?: OrdersControllerGetCustomerOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, ordersControllerGetCustomerOrders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderResponseDto>>;
    })
  );
}

ordersControllerGetCustomerOrders.PATH = '/api/v1/orders/me';
