/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderStatusHistoryResponseDto } from '../../models/order-status-history-response-dto';

export interface OrdersControllerGetOrderTimeline$Params {
  id: string;
}

export function ordersControllerGetOrderTimeline(http: HttpClient, rootUrl: string, params: OrdersControllerGetOrderTimeline$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderStatusHistoryResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, ordersControllerGetOrderTimeline.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderStatusHistoryResponseDto>>;
    })
  );
}

ordersControllerGetOrderTimeline.PATH = '/api/v1/orders/{id}/timeline';
