apiVersion: v1
kind: Service
metadata:
  name: admin-app
  labels:
    app.kubernetes.io/name: admin-app
    app.kubernetes.io/part-of: patheya-express
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
