/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaqResponseDto } from '../../models/faq-response-dto';

export interface FaqControllerFindActive$Params {
  category?: string;
}

export function faqControllerFindActive(http: HttpClient, rootUrl: string, params?: FaqControllerFindActive$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FaqResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, faqControllerFindActive.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FaqResponseDto>>;
    })
  );
}

faqControllerFindActive.PATH = '/api/v1/faqs';
