/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRestaurantDto } from '../../models/create-restaurant-dto';
import { RestaurantResponseDto } from '../../models/restaurant-response-dto';

export interface RestaurantsControllerCreateRestaurant$Params {
      body: CreateRestaurantDto
}

export function restaurantsControllerCreateRestaurant(http: HttpClient, rootUrl: string, params: RestaurantsControllerCreateRestaurant$Params, context?: HttpContext): Observable<StrictHttpResponse<RestaurantResponseDto>> {
  const rb = new RequestBuilder(rootUrl, restaurantsControllerCreateRestaurant.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RestaurantResponseDto>;
    })
  );
}

restaurantsControllerCreateRestaurant.PATH = '/api/v1/restaurants';
