/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedRestaurantsResponseDto } from '../../models/paginated-restaurants-response-dto';

export interface RestaurantsControllerFindAll$Params {
  sortOrder?: 'asc' | 'desc';
  sortBy?: 'name' | 'rating' | 'createdAt';
  openNow?: boolean;
  featured?: boolean;
  cuisine?: any;
  city?: any;
  search?: any;
  limit?: number;
  page?: number;
}

export function restaurantsControllerFindAll(http: HttpClient, rootUrl: string, params?: RestaurantsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedRestaurantsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, restaurantsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('sortOrder', params.sortOrder, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('openNow', params.openNow, {});
    rb.query('featured', params.featured, {});
    rb.query('cuisine', params.cuisine, {});
    rb.query('city', params.city, {});
    rb.query('search', params.search, {});
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedRestaurantsResponseDto>;
    })
  );
}

restaurantsControllerFindAll.PATH = '/api/v1/restaurants';
