/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RestaurantResponseDto } from '../../models/restaurant-response-dto';

export interface RestaurantsControllerRestoreRestaurant$Params {
  id: string;
}

export function restaurantsControllerRestoreRestaurant(http: HttpClient, rootUrl: string, params: RestaurantsControllerRestoreRestaurant$Params, context?: HttpContext): Observable<StrictHttpResponse<RestaurantResponseDto>> {
  const rb = new RequestBuilder(rootUrl, restaurantsControllerRestoreRestaurant.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RestaurantResponseDto>;
    })
  );
}

restaurantsControllerRestoreRestaurant.PATH = '/api/v1/restaurants/{id}/restore';
