/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedReviewsResponseDto } from '../../models/paginated-reviews-response-dto';

export interface ReviewsControllerGetReviews$Params {
  id: string;
  page?: number;
  limit?: number;
}

export function reviewsControllerGetReviews(http: HttpClient, rootUrl: string, params: ReviewsControllerGetReviews$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedReviewsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, reviewsControllerGetReviews.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedReviewsResponseDto>;
    })
  );
}

reviewsControllerGetReviews.PATH = '/api/v1/restaurants/{id}/reviews';
