/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleResponseDto } from '../../models/vehicle-response-dto';

export interface VehiclesControllerList$Params {
}

export function vehiclesControllerList(http: HttpClient, rootUrl: string, params?: VehiclesControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VehicleResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, vehiclesControllerList.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<VehicleResponseDto>>;
    })
  );
}

vehiclesControllerList.PATH = '/api/v1/delivery/vehicles';
