/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleResponseDto } from '../../models/vehicle-response-dto';

export interface VehiclesControllerDeactivate$Params {
  vehicleId: string;
}

export function vehiclesControllerDeactivate(http: HttpClient, rootUrl: string, params: VehiclesControllerDeactivate$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, vehiclesControllerDeactivate.PATH, 'delete');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleResponseDto>;
    })
  );
}

vehiclesControllerDeactivate.PATH = '/api/v1/delivery/vehicles/{vehicleId}';
