/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateVehicleDto } from '../../models/update-vehicle-dto';
import { VehicleResponseDto } from '../../models/vehicle-response-dto';

export interface VehiclesControllerUpdate$Params {
  vehicleId: string;
      body: UpdateVehicleDto
}

export function vehiclesControllerUpdate(http: HttpClient, rootUrl: string, params: VehiclesControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, vehiclesControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('vehicleId', params.vehicleId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleResponseDto>;
    })
  );
}

vehiclesControllerUpdate.PATH = '/api/v1/delivery/vehicles/{vehicleId}';
