/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LivenessResponseDto } from '../../models/liveness-response-dto';

export interface HealthControllerGetLiveness$Params {
}

export function healthControllerGetLiveness(http: HttpClient, rootUrl: string, params?: HealthControllerGetLiveness$Params, context?: HttpContext): Observable<StrictHttpResponse<LivenessResponseDto>> {
  const rb = new RequestBuilder(rootUrl, healthControllerGetLiveness.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LivenessResponseDto>;
    })
  );
}

healthControllerGetLiveness.PATH = '/api/v1/health/live';
