/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { auditControllerGetLogs } from '../fn/audit/audit-controller-get-logs';
import { AuditControllerGetLogs$Params } from '../fn/audit/audit-controller-get-logs';

@Injectable({ providedIn: 'root' })
export class AuditService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `auditControllerGetLogs()` */
  static readonly AuditControllerGetLogsPath = '/api/v1/audit';

  /**
   * Get audit logs.
   *
   * Returns paginated audit logs ordered by newest first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `auditControllerGetLogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  auditControllerGetLogs$Response(params?: AuditControllerGetLogs$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = auditControllerGetLogs(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get audit logs.
   *
   * Returns paginated audit logs ordered by newest first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `auditControllerGetLogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  auditControllerGetLogs(params?: AuditControllerGetLogs$Params, context?: HttpContext): Promise<void> {
    const resp = this.auditControllerGetLogs$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
