/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { cartControllerAddItem } from '../fn/cart/cart-controller-add-item';
import { CartControllerAddItem$Params } from '../fn/cart/cart-controller-add-item';
import { cartControllerClearCart } from '../fn/cart/cart-controller-clear-cart';
import { CartControllerClearCart$Params } from '../fn/cart/cart-controller-clear-cart';
import { cartControllerGetCart } from '../fn/cart/cart-controller-get-cart';
import { CartControllerGetCart$Params } from '../fn/cart/cart-controller-get-cart';
import { cartControllerRemoveItem } from '../fn/cart/cart-controller-remove-item';
import { CartControllerRemoveItem$Params } from '../fn/cart/cart-controller-remove-item';
import { cartControllerUpdateItem } from '../fn/cart/cart-controller-update-item';
import { CartControllerUpdateItem$Params } from '../fn/cart/cart-controller-update-item';
import { CartResponseDto } from '../models/cart-response-dto';

@Injectable({ providedIn: 'root' })
export class CartService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `cartControllerGetCart()` */
  static readonly CartControllerGetCartPath = '/api/v1/cart';

  /**
   * Get my cart.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cartControllerGetCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  cartControllerGetCart$Response(params?: CartControllerGetCart$Params, context?: HttpContext): Promise<StrictHttpResponse<CartResponseDto>> {
    const obs = cartControllerGetCart(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get my cart.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cartControllerGetCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cartControllerGetCart(params?: CartControllerGetCart$Params, context?: HttpContext): Promise<CartResponseDto> {
    const resp = this.cartControllerGetCart$Response(params, context);
    return resp.then((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body);
  }

  /** Path part for operation `cartControllerClearCart()` */
  static readonly CartControllerClearCartPath = '/api/v1/cart';

  /**
   * Clear my cart.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cartControllerClearCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  cartControllerClearCart$Response(params?: CartControllerClearCart$Params, context?: HttpContext): Promise<StrictHttpResponse<CartResponseDto>> {
    const obs = cartControllerClearCart(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Clear my cart.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cartControllerClearCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cartControllerClearCart(params?: CartControllerClearCart$Params, context?: HttpContext): Promise<CartResponseDto> {
    const resp = this.cartControllerClearCart$Response(params, context);
    return resp.then((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body);
  }

  /** Path part for operation `cartControllerAddItem()` */
  static readonly CartControllerAddItemPath = '/api/v1/cart/items';

  /**
   * Add an item to my cart.
   *
   * Returns 409 if the cart already holds items from a different restaurant; resubmit with replaceExisting: true to clear the cart and add the new item instead.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cartControllerAddItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  cartControllerAddItem$Response(params: CartControllerAddItem$Params, context?: HttpContext): Promise<StrictHttpResponse<CartResponseDto>> {
    const obs = cartControllerAddItem(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Add an item to my cart.
   *
   * Returns 409 if the cart already holds items from a different restaurant; resubmit with replaceExisting: true to clear the cart and add the new item instead.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cartControllerAddItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  cartControllerAddItem(params: CartControllerAddItem$Params, context?: HttpContext): Promise<CartResponseDto> {
    const resp = this.cartControllerAddItem$Response(params, context);
    return resp.then((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body);
  }

  /** Path part for operation `cartControllerRemoveItem()` */
  static readonly CartControllerRemoveItemPath = '/api/v1/cart/items/{itemId}';

  /**
   * Remove an item from my cart.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cartControllerRemoveItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  cartControllerRemoveItem$Response(params: CartControllerRemoveItem$Params, context?: HttpContext): Promise<StrictHttpResponse<CartResponseDto>> {
    const obs = cartControllerRemoveItem(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Remove an item from my cart.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cartControllerRemoveItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cartControllerRemoveItem(params: CartControllerRemoveItem$Params, context?: HttpContext): Promise<CartResponseDto> {
    const resp = this.cartControllerRemoveItem$Response(params, context);
    return resp.then((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body);
  }

  /** Path part for operation `cartControllerUpdateItem()` */
  static readonly CartControllerUpdateItemPath = '/api/v1/cart/items/{itemId}';

  /**
   * Update a cart item quantity.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cartControllerUpdateItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  cartControllerUpdateItem$Response(params: CartControllerUpdateItem$Params, context?: HttpContext): Promise<StrictHttpResponse<CartResponseDto>> {
    const obs = cartControllerUpdateItem(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update a cart item quantity.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cartControllerUpdateItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  cartControllerUpdateItem(params: CartControllerUpdateItem$Params, context?: HttpContext): Promise<CartResponseDto> {
    const resp = this.cartControllerUpdateItem$Response(params, context);
    return resp.then((r: StrictHttpResponse<CartResponseDto>): CartResponseDto => r.body);
  }

}
