/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CuisineResponseDto } from '../models/cuisine-response-dto';
import { cuisinesControllerFindAll } from '../fn/cuisines/cuisines-controller-find-all';
import { CuisinesControllerFindAll$Params } from '../fn/cuisines/cuisines-controller-find-all';

@Injectable({ providedIn: 'root' })
export class CuisinesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `cuisinesControllerFindAll()` */
  static readonly CuisinesControllerFindAllPath = '/api/v1/cuisines';

  /**
   * Get all cuisines.
   *
   * Public — returns the cuisine taxonomy, used for discovery filter chips and typeahead. Optionally filtered by a search prefix/substring.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cuisinesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  cuisinesControllerFindAll$Response(params?: CuisinesControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CuisineResponseDto>>> {
    const obs = cuisinesControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all cuisines.
   *
   * Public — returns the cuisine taxonomy, used for discovery filter chips and typeahead. Optionally filtered by a search prefix/substring.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cuisinesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  cuisinesControllerFindAll(params?: CuisinesControllerFindAll$Params, context?: HttpContext): Promise<Array<CuisineResponseDto>> {
    const resp = this.cuisinesControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CuisineResponseDto>>): Array<CuisineResponseDto> => r.body);
  }

}
