/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { customerHomeControllerGetHome } from '../fn/customer/customer-home-controller-get-home';
import { CustomerHomeControllerGetHome$Params } from '../fn/customer/customer-home-controller-get-home';
import { CustomerHomeResponseDto } from '../models/customer-home-response-dto';

@Injectable({ providedIn: 'root' })
export class CustomerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `customerHomeControllerGetHome()` */
  static readonly CustomerHomeControllerGetHomePath = '/api/v1/customer/home';

  /**
   * Get customer home screen.
   *
   * Public — composes banners, featured/nearby/popular/recommended restaurants, and cuisines into a single response for the customer app's home screen. Nearby/recommended sections are empty until lat/lng are supplied.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `customerHomeControllerGetHome()` instead.
   *
   * This method doesn't expect any request body.
   */
  customerHomeControllerGetHome$Response(params?: CustomerHomeControllerGetHome$Params, context?: HttpContext): Promise<StrictHttpResponse<CustomerHomeResponseDto>> {
    const obs = customerHomeControllerGetHome(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get customer home screen.
   *
   * Public — composes banners, featured/nearby/popular/recommended restaurants, and cuisines into a single response for the customer app's home screen. Nearby/recommended sections are empty until lat/lng are supplied.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `customerHomeControllerGetHome$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  customerHomeControllerGetHome(params?: CustomerHomeControllerGetHome$Params, context?: HttpContext): Promise<CustomerHomeResponseDto> {
    const resp = this.customerHomeControllerGetHome$Response(params, context);
    return resp.then((r: StrictHttpResponse<CustomerHomeResponseDto>): CustomerHomeResponseDto => r.body);
  }

}
