/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DeliveryDocumentResponseDto } from '../models/delivery-document-response-dto';
import { deliveryDocumentsControllerFindAll } from '../fn/delivery-documents/delivery-documents-controller-find-all';
import { DeliveryDocumentsControllerFindAll$Params } from '../fn/delivery-documents/delivery-documents-controller-find-all';
import { deliveryDocumentsControllerHistory } from '../fn/delivery-documents/delivery-documents-controller-history';
import { DeliveryDocumentsControllerHistory$Params } from '../fn/delivery-documents/delivery-documents-controller-history';
import { deliveryDocumentsControllerRemove } from '../fn/delivery-documents/delivery-documents-controller-remove';
import { DeliveryDocumentsControllerRemove$Params } from '../fn/delivery-documents/delivery-documents-controller-remove';
import { deliveryDocumentsControllerUpload } from '../fn/delivery-documents/delivery-documents-controller-upload';
import { DeliveryDocumentsControllerUpload$Params } from '../fn/delivery-documents/delivery-documents-controller-upload';
import { DocumentVersionResponseDto } from '../models/document-version-response-dto';

@Injectable({ providedIn: 'root' })
export class DeliveryDocumentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `deliveryDocumentsControllerFindAll()` */
  static readonly DeliveryDocumentsControllerFindAllPath = '/api/v1/delivery/documents';

  /**
   * List the latest version of every one of my documents.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryDocumentsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryDocumentsControllerFindAll$Response(params?: DeliveryDocumentsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DeliveryDocumentResponseDto>>> {
    const obs = deliveryDocumentsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List the latest version of every one of my documents.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryDocumentsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryDocumentsControllerFindAll(params?: DeliveryDocumentsControllerFindAll$Params, context?: HttpContext): Promise<Array<DeliveryDocumentResponseDto>> {
    const resp = this.deliveryDocumentsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DeliveryDocumentResponseDto>>): Array<DeliveryDocumentResponseDto> => r.body);
  }

  /** Path part for operation `deliveryDocumentsControllerUpload()` */
  static readonly DeliveryDocumentsControllerUploadPath = '/api/v1/delivery/documents';

  /**
   * Upload a document.
   *
   * Set previousVersionId to replace an existing document — the old version is marked isLatest=false rather than deleted.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryDocumentsControllerUpload()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  deliveryDocumentsControllerUpload$Response(params: DeliveryDocumentsControllerUpload$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryDocumentResponseDto>> {
    const obs = deliveryDocumentsControllerUpload(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Upload a document.
   *
   * Set previousVersionId to replace an existing document — the old version is marked isLatest=false rather than deleted.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryDocumentsControllerUpload$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  deliveryDocumentsControllerUpload(params: DeliveryDocumentsControllerUpload$Params, context?: HttpContext): Promise<DeliveryDocumentResponseDto> {
    const resp = this.deliveryDocumentsControllerUpload$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryDocumentResponseDto>): DeliveryDocumentResponseDto => r.body);
  }

  /** Path part for operation `deliveryDocumentsControllerHistory()` */
  static readonly DeliveryDocumentsControllerHistoryPath = '/api/v1/delivery/documents/{documentType}/history';

  /**
   * Version history for one document type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryDocumentsControllerHistory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryDocumentsControllerHistory$Response(params: DeliveryDocumentsControllerHistory$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DocumentVersionResponseDto>>> {
    const obs = deliveryDocumentsControllerHistory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Version history for one document type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryDocumentsControllerHistory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryDocumentsControllerHistory(params: DeliveryDocumentsControllerHistory$Params, context?: HttpContext): Promise<Array<DocumentVersionResponseDto>> {
    const resp = this.deliveryDocumentsControllerHistory$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DocumentVersionResponseDto>>): Array<DocumentVersionResponseDto> => r.body);
  }

  /** Path part for operation `deliveryDocumentsControllerRemove()` */
  static readonly DeliveryDocumentsControllerRemovePath = '/api/v1/delivery/documents/{documentId}';

  /**
   * Remove a document (soft delete).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryDocumentsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryDocumentsControllerRemove$Response(params: DeliveryDocumentsControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = deliveryDocumentsControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Remove a document (soft delete).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryDocumentsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryDocumentsControllerRemove(params: DeliveryDocumentsControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.deliveryDocumentsControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
