/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deliveryControllerGetAssignedOrders } from '../fn/delivery/delivery-controller-get-assigned-orders';
import { DeliveryControllerGetAssignedOrders$Params } from '../fn/delivery/delivery-controller-get-assigned-orders';
import { deliveryControllerGetMe } from '../fn/delivery/delivery-controller-get-me';
import { DeliveryControllerGetMe$Params } from '../fn/delivery/delivery-controller-get-me';
import { deliveryControllerGoAvailable } from '../fn/delivery/delivery-controller-go-available';
import { DeliveryControllerGoAvailable$Params } from '../fn/delivery/delivery-controller-go-available';
import { deliveryControllerGoOffline } from '../fn/delivery/delivery-controller-go-offline';
import { DeliveryControllerGoOffline$Params } from '../fn/delivery/delivery-controller-go-offline';
import { deliveryControllerOnboardPartner } from '../fn/delivery/delivery-controller-onboard-partner';
import { DeliveryControllerOnboardPartner$Params } from '../fn/delivery/delivery-controller-onboard-partner';
import { deliveryControllerUpdateDeliveryStatus } from '../fn/delivery/delivery-controller-update-delivery-status';
import { DeliveryControllerUpdateDeliveryStatus$Params } from '../fn/delivery/delivery-controller-update-delivery-status';
import { DeliveryPartnerResponseDto } from '../models/delivery-partner-response-dto';
import { OrderResponseDto } from '../models/order-response-dto';

@Injectable({ providedIn: 'root' })
export class DeliveryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `deliveryControllerGetMe()` */
  static readonly DeliveryControllerGetMePath = '/api/v1/delivery/me';

  /**
   * Get my delivery partner profile.
   *
   * Returns the delivery partner profile for the authenticated user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryControllerGetMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGetMe$Response(params?: DeliveryControllerGetMe$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryPartnerResponseDto>> {
    const obs = deliveryControllerGetMe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get my delivery partner profile.
   *
   * Returns the delivery partner profile for the authenticated user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryControllerGetMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGetMe(params?: DeliveryControllerGetMe$Params, context?: HttpContext): Promise<DeliveryPartnerResponseDto> {
    const resp = this.deliveryControllerGetMe$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryPartnerResponseDto>): DeliveryPartnerResponseDto => r.body);
  }

  /** Path part for operation `deliveryControllerOnboardPartner()` */
  static readonly DeliveryControllerOnboardPartnerPath = '/api/v1/delivery/onboard';

  /**
   * Onboard delivery partner.
   *
   * Register the authenticated user as a delivery partner.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryControllerOnboardPartner()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deliveryControllerOnboardPartner$Response(params: DeliveryControllerOnboardPartner$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryPartnerResponseDto>> {
    const obs = deliveryControllerOnboardPartner(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Onboard delivery partner.
   *
   * Register the authenticated user as a delivery partner.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryControllerOnboardPartner$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deliveryControllerOnboardPartner(params: DeliveryControllerOnboardPartner$Params, context?: HttpContext): Promise<DeliveryPartnerResponseDto> {
    const resp = this.deliveryControllerOnboardPartner$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryPartnerResponseDto>): DeliveryPartnerResponseDto => r.body);
  }

  /** Path part for operation `deliveryControllerGoAvailable()` */
  static readonly DeliveryControllerGoAvailablePath = '/api/v1/delivery/available';

  /**
   * Set delivery partner available.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryControllerGoAvailable()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGoAvailable$Response(params?: DeliveryControllerGoAvailable$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryPartnerResponseDto>> {
    const obs = deliveryControllerGoAvailable(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Set delivery partner available.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryControllerGoAvailable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGoAvailable(params?: DeliveryControllerGoAvailable$Params, context?: HttpContext): Promise<DeliveryPartnerResponseDto> {
    const resp = this.deliveryControllerGoAvailable$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryPartnerResponseDto>): DeliveryPartnerResponseDto => r.body);
  }

  /** Path part for operation `deliveryControllerGoOffline()` */
  static readonly DeliveryControllerGoOfflinePath = '/api/v1/delivery/offline';

  /**
   * Set delivery partner offline.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryControllerGoOffline()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGoOffline$Response(params?: DeliveryControllerGoOffline$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryPartnerResponseDto>> {
    const obs = deliveryControllerGoOffline(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Set delivery partner offline.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryControllerGoOffline$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGoOffline(params?: DeliveryControllerGoOffline$Params, context?: HttpContext): Promise<DeliveryPartnerResponseDto> {
    const resp = this.deliveryControllerGoOffline$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryPartnerResponseDto>): DeliveryPartnerResponseDto => r.body);
  }

  /** Path part for operation `deliveryControllerGetAssignedOrders()` */
  static readonly DeliveryControllerGetAssignedOrdersPath = '/api/v1/delivery/orders';

  /**
   * Get assigned orders.
   *
   * Returns all orders assigned to the authenticated delivery partner.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryControllerGetAssignedOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGetAssignedOrders$Response(params?: DeliveryControllerGetAssignedOrders$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<OrderResponseDto>>> {
    const obs = deliveryControllerGetAssignedOrders(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get assigned orders.
   *
   * Returns all orders assigned to the authenticated delivery partner.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryControllerGetAssignedOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryControllerGetAssignedOrders(params?: DeliveryControllerGetAssignedOrders$Params, context?: HttpContext): Promise<Array<OrderResponseDto>> {
    const resp = this.deliveryControllerGetAssignedOrders$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<OrderResponseDto>>): Array<OrderResponseDto> => r.body);
  }

  /** Path part for operation `deliveryControllerUpdateDeliveryStatus()` */
  static readonly DeliveryControllerUpdateDeliveryStatusPath = '/api/v1/delivery/orders/{orderId}/status';

  /**
   * Update delivery status.
   *
   * Update delivery progress for an assigned order.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryControllerUpdateDeliveryStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deliveryControllerUpdateDeliveryStatus$Response(params: DeliveryControllerUpdateDeliveryStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<OrderResponseDto>> {
    const obs = deliveryControllerUpdateDeliveryStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update delivery status.
   *
   * Update delivery progress for an assigned order.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryControllerUpdateDeliveryStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deliveryControllerUpdateDeliveryStatus(params: DeliveryControllerUpdateDeliveryStatus$Params, context?: HttpContext): Promise<OrderResponseDto> {
    const resp = this.deliveryControllerUpdateDeliveryStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<OrderResponseDto>): OrderResponseDto => r.body);
  }

}
