/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminDocumentsControllerFindAll } from '../fn/delivery-documents-admin/admin-documents-controller-find-all';
import { AdminDocumentsControllerFindAll$Params } from '../fn/delivery-documents-admin/admin-documents-controller-find-all';
import { adminDocumentsControllerHistory } from '../fn/delivery-documents-admin/admin-documents-controller-history';
import { AdminDocumentsControllerHistory$Params } from '../fn/delivery-documents-admin/admin-documents-controller-history';
import { adminDocumentsControllerReject } from '../fn/delivery-documents-admin/admin-documents-controller-reject';
import { AdminDocumentsControllerReject$Params } from '../fn/delivery-documents-admin/admin-documents-controller-reject';
import { adminDocumentsControllerVerify } from '../fn/delivery-documents-admin/admin-documents-controller-verify';
import { AdminDocumentsControllerVerify$Params } from '../fn/delivery-documents-admin/admin-documents-controller-verify';
import { DeliveryDocumentResponseDto } from '../models/delivery-document-response-dto';
import { DocumentVersionResponseDto } from '../models/document-version-response-dto';

@Injectable({ providedIn: 'root' })
export class DeliveryDocumentsAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminDocumentsControllerFindAll()` */
  static readonly AdminDocumentsControllerFindAllPath = '/api/v1/delivery/admin/{deliveryPartnerId}/documents';

  /**
   * List the latest version of every document for a partner.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminDocumentsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminDocumentsControllerFindAll$Response(params: AdminDocumentsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DeliveryDocumentResponseDto>>> {
    const obs = adminDocumentsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List the latest version of every document for a partner.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminDocumentsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminDocumentsControllerFindAll(params: AdminDocumentsControllerFindAll$Params, context?: HttpContext): Promise<Array<DeliveryDocumentResponseDto>> {
    const resp = this.adminDocumentsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DeliveryDocumentResponseDto>>): Array<DeliveryDocumentResponseDto> => r.body);
  }

  /** Path part for operation `adminDocumentsControllerHistory()` */
  static readonly AdminDocumentsControllerHistoryPath = '/api/v1/delivery/admin/{deliveryPartnerId}/documents/{documentType}/history';

  /**
   * Version history for one document type.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminDocumentsControllerHistory()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminDocumentsControllerHistory$Response(params: AdminDocumentsControllerHistory$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DocumentVersionResponseDto>>> {
    const obs = adminDocumentsControllerHistory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Version history for one document type.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminDocumentsControllerHistory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminDocumentsControllerHistory(params: AdminDocumentsControllerHistory$Params, context?: HttpContext): Promise<Array<DocumentVersionResponseDto>> {
    const resp = this.adminDocumentsControllerHistory$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DocumentVersionResponseDto>>): Array<DocumentVersionResponseDto> => r.body);
  }

  /** Path part for operation `adminDocumentsControllerVerify()` */
  static readonly AdminDocumentsControllerVerifyPath = '/api/v1/delivery/admin/{deliveryPartnerId}/documents/{documentId}/verify';

  /**
   * Verify a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminDocumentsControllerVerify()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminDocumentsControllerVerify$Response(params: AdminDocumentsControllerVerify$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryDocumentResponseDto>> {
    const obs = adminDocumentsControllerVerify(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Verify a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminDocumentsControllerVerify$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminDocumentsControllerVerify(params: AdminDocumentsControllerVerify$Params, context?: HttpContext): Promise<DeliveryDocumentResponseDto> {
    const resp = this.adminDocumentsControllerVerify$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryDocumentResponseDto>): DeliveryDocumentResponseDto => r.body);
  }

  /** Path part for operation `adminDocumentsControllerReject()` */
  static readonly AdminDocumentsControllerRejectPath = '/api/v1/delivery/admin/{deliveryPartnerId}/documents/{documentId}/reject';

  /**
   * Reject a document.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminDocumentsControllerReject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminDocumentsControllerReject$Response(params: AdminDocumentsControllerReject$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryDocumentResponseDto>> {
    const obs = adminDocumentsControllerReject(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Reject a document.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminDocumentsControllerReject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  adminDocumentsControllerReject(params: AdminDocumentsControllerReject$Params, context?: HttpContext): Promise<DeliveryDocumentResponseDto> {
    const resp = this.adminDocumentsControllerReject$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryDocumentResponseDto>): DeliveryDocumentResponseDto => r.body);
  }

}
