/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminComplianceControllerGetSnapshot } from '../fn/delivery-compliance-admin/admin-compliance-controller-get-snapshot';
import { AdminComplianceControllerGetSnapshot$Params } from '../fn/delivery-compliance-admin/admin-compliance-controller-get-snapshot';
import { DeliveryComplianceResponseDto } from '../models/delivery-compliance-response-dto';

@Injectable({ providedIn: 'root' })
export class DeliveryComplianceAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminComplianceControllerGetSnapshot()` */
  static readonly AdminComplianceControllerGetSnapshotPath = '/api/v1/delivery/admin/{deliveryPartnerId}/compliance';

  /**
   * A partner's compliance/readiness snapshot.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminComplianceControllerGetSnapshot()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminComplianceControllerGetSnapshot$Response(params: AdminComplianceControllerGetSnapshot$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryComplianceResponseDto>> {
    const obs = adminComplianceControllerGetSnapshot(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * A partner's compliance/readiness snapshot.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminComplianceControllerGetSnapshot$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminComplianceControllerGetSnapshot(params: AdminComplianceControllerGetSnapshot$Params, context?: HttpContext): Promise<DeliveryComplianceResponseDto> {
    const resp = this.adminComplianceControllerGetSnapshot$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryComplianceResponseDto>): DeliveryComplianceResponseDto => r.body);
  }

}
