/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deliveryComplianceControllerGetSnapshot } from '../fn/delivery-compliance/delivery-compliance-controller-get-snapshot';
import { DeliveryComplianceControllerGetSnapshot$Params } from '../fn/delivery-compliance/delivery-compliance-controller-get-snapshot';
import { DeliveryComplianceResponseDto } from '../models/delivery-compliance-response-dto';

@Injectable({ providedIn: 'root' })
export class DeliveryComplianceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `deliveryComplianceControllerGetSnapshot()` */
  static readonly DeliveryComplianceControllerGetSnapshotPath = '/api/v1/delivery/compliance';

  /**
   * My compliance/readiness snapshot.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryComplianceControllerGetSnapshot()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryComplianceControllerGetSnapshot$Response(params?: DeliveryComplianceControllerGetSnapshot$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryComplianceResponseDto>> {
    const obs = deliveryComplianceControllerGetSnapshot(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * My compliance/readiness snapshot.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryComplianceControllerGetSnapshot$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryComplianceControllerGetSnapshot(params?: DeliveryComplianceControllerGetSnapshot$Params, context?: HttpContext): Promise<DeliveryComplianceResponseDto> {
    const resp = this.deliveryComplianceControllerGetSnapshot$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryComplianceResponseDto>): DeliveryComplianceResponseDto => r.body);
  }

}
