/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deliveryOnboardingControllerCompleteStep } from '../fn/delivery-onboarding/delivery-onboarding-controller-complete-step';
import { DeliveryOnboardingControllerCompleteStep$Params } from '../fn/delivery-onboarding/delivery-onboarding-controller-complete-step';
import { deliveryOnboardingControllerGetState } from '../fn/delivery-onboarding/delivery-onboarding-controller-get-state';
import { DeliveryOnboardingControllerGetState$Params } from '../fn/delivery-onboarding/delivery-onboarding-controller-get-state';
import { deliveryOnboardingControllerSubmit } from '../fn/delivery-onboarding/delivery-onboarding-controller-submit';
import { DeliveryOnboardingControllerSubmit$Params } from '../fn/delivery-onboarding/delivery-onboarding-controller-submit';
import { DeliveryOnboardingResponseDto } from '../models/delivery-onboarding-response-dto';

@Injectable({ providedIn: 'root' })
export class DeliveryOnboardingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `deliveryOnboardingControllerGetState()` */
  static readonly DeliveryOnboardingControllerGetStatePath = '/api/v1/delivery/onboarding';

  /**
   * Get my onboarding progress.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryOnboardingControllerGetState()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryOnboardingControllerGetState$Response(params?: DeliveryOnboardingControllerGetState$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryOnboardingResponseDto>> {
    const obs = deliveryOnboardingControllerGetState(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get my onboarding progress.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryOnboardingControllerGetState$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryOnboardingControllerGetState(params?: DeliveryOnboardingControllerGetState$Params, context?: HttpContext): Promise<DeliveryOnboardingResponseDto> {
    const resp = this.deliveryOnboardingControllerGetState$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryOnboardingResponseDto>): DeliveryOnboardingResponseDto => r.body);
  }

  /** Path part for operation `deliveryOnboardingControllerCompleteStep()` */
  static readonly DeliveryOnboardingControllerCompleteStepPath = '/api/v1/delivery/onboarding/steps/{step}';

  /**
   * Mark a wizard step complete.
   *
   * Records wizard progress only — the step's actual data is saved via the existing dedicated endpoint for that section (profile, vehicles, documents, bank account) before this is called.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryOnboardingControllerCompleteStep()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryOnboardingControllerCompleteStep$Response(params: DeliveryOnboardingControllerCompleteStep$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryOnboardingResponseDto>> {
    const obs = deliveryOnboardingControllerCompleteStep(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Mark a wizard step complete.
   *
   * Records wizard progress only — the step's actual data is saved via the existing dedicated endpoint for that section (profile, vehicles, documents, bank account) before this is called.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryOnboardingControllerCompleteStep$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deliveryOnboardingControllerCompleteStep(params: DeliveryOnboardingControllerCompleteStep$Params, context?: HttpContext): Promise<DeliveryOnboardingResponseDto> {
    const resp = this.deliveryOnboardingControllerCompleteStep$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryOnboardingResponseDto>): DeliveryOnboardingResponseDto => r.body);
  }

  /** Path part for operation `deliveryOnboardingControllerSubmit()` */
  static readonly DeliveryOnboardingControllerSubmitPath = '/api/v1/delivery/onboarding/submit';

  /**
   * Submit the onboarding application for review.
   *
   * Requires steps 1-11 complete and acceptedTerms=true. Delegates to the existing verification submit flow.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deliveryOnboardingControllerSubmit()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deliveryOnboardingControllerSubmit$Response(params: DeliveryOnboardingControllerSubmit$Params, context?: HttpContext): Promise<StrictHttpResponse<DeliveryOnboardingResponseDto>> {
    const obs = deliveryOnboardingControllerSubmit(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Submit the onboarding application for review.
   *
   * Requires steps 1-11 complete and acceptedTerms=true. Delegates to the existing verification submit flow.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deliveryOnboardingControllerSubmit$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  deliveryOnboardingControllerSubmit(params: DeliveryOnboardingControllerSubmit$Params, context?: HttpContext): Promise<DeliveryOnboardingResponseDto> {
    const resp = this.deliveryOnboardingControllerSubmit$Response(params, context);
    return resp.then((r: StrictHttpResponse<DeliveryOnboardingResponseDto>): DeliveryOnboardingResponseDto => r.body);
  }

}
