/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DeliveryAssignmentResponseDto } from '../models/delivery-assignment-response-dto';
import { DispatchActionResponseDto } from '../models/dispatch-action-response-dto';
import { dispatchControllerAcceptAssignment } from '../fn/dispatch/dispatch-controller-accept-assignment';
import { DispatchControllerAcceptAssignment$Params } from '../fn/dispatch/dispatch-controller-accept-assignment';
import { dispatchControllerGetAssignments } from '../fn/dispatch/dispatch-controller-get-assignments';
import { DispatchControllerGetAssignments$Params } from '../fn/dispatch/dispatch-controller-get-assignments';
import { dispatchControllerRejectAssignment } from '../fn/dispatch/dispatch-controller-reject-assignment';
import { DispatchControllerRejectAssignment$Params } from '../fn/dispatch/dispatch-controller-reject-assignment';

@Injectable({ providedIn: 'root' })
export class DispatchService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `dispatchControllerGetAssignments()` */
  static readonly DispatchControllerGetAssignmentsPath = '/api/v1/dispatch/assignments';

  /**
   * Get delivery partner assignments.
   *
   * Returns all delivery assignments assigned to the authenticated delivery partner, optionally narrowed to one status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dispatchControllerGetAssignments()` instead.
   *
   * This method doesn't expect any request body.
   */
  dispatchControllerGetAssignments$Response(params?: DispatchControllerGetAssignments$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<DeliveryAssignmentResponseDto>>> {
    const obs = dispatchControllerGetAssignments(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get delivery partner assignments.
   *
   * Returns all delivery assignments assigned to the authenticated delivery partner, optionally narrowed to one status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dispatchControllerGetAssignments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dispatchControllerGetAssignments(params?: DispatchControllerGetAssignments$Params, context?: HttpContext): Promise<Array<DeliveryAssignmentResponseDto>> {
    const resp = this.dispatchControllerGetAssignments$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<DeliveryAssignmentResponseDto>>): Array<DeliveryAssignmentResponseDto> => r.body);
  }

  /** Path part for operation `dispatchControllerAcceptAssignment()` */
  static readonly DispatchControllerAcceptAssignmentPath = '/api/v1/dispatch/assignments/{id}/accept';

  /**
   * Accept delivery assignment.
   *
   * Accept a pending delivery assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dispatchControllerAcceptAssignment()` instead.
   *
   * This method doesn't expect any request body.
   */
  dispatchControllerAcceptAssignment$Response(params: DispatchControllerAcceptAssignment$Params, context?: HttpContext): Promise<StrictHttpResponse<DispatchActionResponseDto>> {
    const obs = dispatchControllerAcceptAssignment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Accept delivery assignment.
   *
   * Accept a pending delivery assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dispatchControllerAcceptAssignment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dispatchControllerAcceptAssignment(params: DispatchControllerAcceptAssignment$Params, context?: HttpContext): Promise<DispatchActionResponseDto> {
    const resp = this.dispatchControllerAcceptAssignment$Response(params, context);
    return resp.then((r: StrictHttpResponse<DispatchActionResponseDto>): DispatchActionResponseDto => r.body);
  }

  /** Path part for operation `dispatchControllerRejectAssignment()` */
  static readonly DispatchControllerRejectAssignmentPath = '/api/v1/dispatch/assignments/{id}/reject';

  /**
   * Reject delivery assignment.
   *
   * Reject a pending delivery assignment.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `dispatchControllerRejectAssignment()` instead.
   *
   * This method doesn't expect any request body.
   */
  dispatchControllerRejectAssignment$Response(params: DispatchControllerRejectAssignment$Params, context?: HttpContext): Promise<StrictHttpResponse<DispatchActionResponseDto>> {
    const obs = dispatchControllerRejectAssignment(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Reject delivery assignment.
   *
   * Reject a pending delivery assignment.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `dispatchControllerRejectAssignment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  dispatchControllerRejectAssignment(params: DispatchControllerRejectAssignment$Params, context?: HttpContext): Promise<DispatchActionResponseDto> {
    const resp = this.dispatchControllerRejectAssignment$Response(params, context);
    return resp.then((r: StrictHttpResponse<DispatchActionResponseDto>): DispatchActionResponseDto => r.body);
  }

}
