/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { favoritesControllerAddMenuItemFavorite } from '../fn/favorites/favorites-controller-add-menu-item-favorite';
import { FavoritesControllerAddMenuItemFavorite$Params } from '../fn/favorites/favorites-controller-add-menu-item-favorite';
import { favoritesControllerAddRestaurantFavorite } from '../fn/favorites/favorites-controller-add-restaurant-favorite';
import { FavoritesControllerAddRestaurantFavorite$Params } from '../fn/favorites/favorites-controller-add-restaurant-favorite';
import { favoritesControllerGetFavoriteMenuItems } from '../fn/favorites/favorites-controller-get-favorite-menu-items';
import { FavoritesControllerGetFavoriteMenuItems$Params } from '../fn/favorites/favorites-controller-get-favorite-menu-items';
import { favoritesControllerGetFavoriteRestaurants } from '../fn/favorites/favorites-controller-get-favorite-restaurants';
import { FavoritesControllerGetFavoriteRestaurants$Params } from '../fn/favorites/favorites-controller-get-favorite-restaurants';
import { favoritesControllerGetMenuItemFavoriteStatus } from '../fn/favorites/favorites-controller-get-menu-item-favorite-status';
import { FavoritesControllerGetMenuItemFavoriteStatus$Params } from '../fn/favorites/favorites-controller-get-menu-item-favorite-status';
import { favoritesControllerGetRestaurantFavoriteStatus } from '../fn/favorites/favorites-controller-get-restaurant-favorite-status';
import { FavoritesControllerGetRestaurantFavoriteStatus$Params } from '../fn/favorites/favorites-controller-get-restaurant-favorite-status';
import { favoritesControllerRemoveMenuItemFavorite } from '../fn/favorites/favorites-controller-remove-menu-item-favorite';
import { FavoritesControllerRemoveMenuItemFavorite$Params } from '../fn/favorites/favorites-controller-remove-menu-item-favorite';
import { favoritesControllerRemoveRestaurantFavorite } from '../fn/favorites/favorites-controller-remove-restaurant-favorite';
import { FavoritesControllerRemoveRestaurantFavorite$Params } from '../fn/favorites/favorites-controller-remove-restaurant-favorite';
import { FavoriteStatusItemDto } from '../models/favorite-status-item-dto';
import { FavoriteToggleResponseDto } from '../models/favorite-toggle-response-dto';
import { PaginatedFavoriteMenuItemsResponseDto } from '../models/paginated-favorite-menu-items-response-dto';
import { PaginatedRestaurantSummariesResponseDto } from '../models/paginated-restaurant-summaries-response-dto';

@Injectable({ providedIn: 'root' })
export class FavoritesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `favoritesControllerGetFavoriteRestaurants()` */
  static readonly FavoritesControllerGetFavoriteRestaurantsPath = '/api/v1/favorites/restaurants';

  /**
   * List the current customer's favorite restaurants.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerGetFavoriteRestaurants()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetFavoriteRestaurants$Response(params?: FavoritesControllerGetFavoriteRestaurants$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedRestaurantSummariesResponseDto>> {
    const obs = favoritesControllerGetFavoriteRestaurants(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List the current customer's favorite restaurants.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerGetFavoriteRestaurants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetFavoriteRestaurants(params?: FavoritesControllerGetFavoriteRestaurants$Params, context?: HttpContext): Promise<PaginatedRestaurantSummariesResponseDto> {
    const resp = this.favoritesControllerGetFavoriteRestaurants$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedRestaurantSummariesResponseDto>): PaginatedRestaurantSummariesResponseDto => r.body);
  }

  /** Path part for operation `favoritesControllerGetRestaurantFavoriteStatus()` */
  static readonly FavoritesControllerGetRestaurantFavoriteStatusPath = '/api/v1/favorites/restaurants/status';

  /**
   * Bulk-check favorite status for a set of restaurant ids.
   *
   * Accepts a comma-separated list of restaurant ids and returns their favorite status in a single request, so restaurant cards on a listing page never issue one favorite-status request each.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerGetRestaurantFavoriteStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetRestaurantFavoriteStatus$Response(params: FavoritesControllerGetRestaurantFavoriteStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FavoriteStatusItemDto>>> {
    const obs = favoritesControllerGetRestaurantFavoriteStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Bulk-check favorite status for a set of restaurant ids.
   *
   * Accepts a comma-separated list of restaurant ids and returns their favorite status in a single request, so restaurant cards on a listing page never issue one favorite-status request each.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerGetRestaurantFavoriteStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetRestaurantFavoriteStatus(params: FavoritesControllerGetRestaurantFavoriteStatus$Params, context?: HttpContext): Promise<Array<FavoriteStatusItemDto>> {
    const resp = this.favoritesControllerGetRestaurantFavoriteStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FavoriteStatusItemDto>>): Array<FavoriteStatusItemDto> => r.body);
  }

  /** Path part for operation `favoritesControllerAddRestaurantFavorite()` */
  static readonly FavoritesControllerAddRestaurantFavoritePath = '/api/v1/favorites/restaurants/{restaurantId}';

  /**
   * Add a restaurant to favorites.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerAddRestaurantFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerAddRestaurantFavorite$Response(params: FavoritesControllerAddRestaurantFavorite$Params, context?: HttpContext): Promise<StrictHttpResponse<FavoriteToggleResponseDto>> {
    const obs = favoritesControllerAddRestaurantFavorite(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Add a restaurant to favorites.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerAddRestaurantFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerAddRestaurantFavorite(params: FavoritesControllerAddRestaurantFavorite$Params, context?: HttpContext): Promise<FavoriteToggleResponseDto> {
    const resp = this.favoritesControllerAddRestaurantFavorite$Response(params, context);
    return resp.then((r: StrictHttpResponse<FavoriteToggleResponseDto>): FavoriteToggleResponseDto => r.body);
  }

  /** Path part for operation `favoritesControllerRemoveRestaurantFavorite()` */
  static readonly FavoritesControllerRemoveRestaurantFavoritePath = '/api/v1/favorites/restaurants/{restaurantId}';

  /**
   * Remove a restaurant from favorites.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerRemoveRestaurantFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerRemoveRestaurantFavorite$Response(params: FavoritesControllerRemoveRestaurantFavorite$Params, context?: HttpContext): Promise<StrictHttpResponse<FavoriteToggleResponseDto>> {
    const obs = favoritesControllerRemoveRestaurantFavorite(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Remove a restaurant from favorites.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerRemoveRestaurantFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerRemoveRestaurantFavorite(params: FavoritesControllerRemoveRestaurantFavorite$Params, context?: HttpContext): Promise<FavoriteToggleResponseDto> {
    const resp = this.favoritesControllerRemoveRestaurantFavorite$Response(params, context);
    return resp.then((r: StrictHttpResponse<FavoriteToggleResponseDto>): FavoriteToggleResponseDto => r.body);
  }

  /** Path part for operation `favoritesControllerGetFavoriteMenuItems()` */
  static readonly FavoritesControllerGetFavoriteMenuItemsPath = '/api/v1/favorites/menu-items';

  /**
   * List the current customer's favorite menu items.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerGetFavoriteMenuItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetFavoriteMenuItems$Response(params?: FavoritesControllerGetFavoriteMenuItems$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedFavoriteMenuItemsResponseDto>> {
    const obs = favoritesControllerGetFavoriteMenuItems(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List the current customer's favorite menu items.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerGetFavoriteMenuItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetFavoriteMenuItems(params?: FavoritesControllerGetFavoriteMenuItems$Params, context?: HttpContext): Promise<PaginatedFavoriteMenuItemsResponseDto> {
    const resp = this.favoritesControllerGetFavoriteMenuItems$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedFavoriteMenuItemsResponseDto>): PaginatedFavoriteMenuItemsResponseDto => r.body);
  }

  /** Path part for operation `favoritesControllerGetMenuItemFavoriteStatus()` */
  static readonly FavoritesControllerGetMenuItemFavoriteStatusPath = '/api/v1/favorites/menu-items/status';

  /**
   * Bulk-check favorite status for a set of menu item ids.
   *
   * Accepts a comma-separated list of menu item ids and returns their favorite status in a single request, so menu item cards never issue one favorite-status request each.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerGetMenuItemFavoriteStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetMenuItemFavoriteStatus$Response(params: FavoritesControllerGetMenuItemFavoriteStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FavoriteStatusItemDto>>> {
    const obs = favoritesControllerGetMenuItemFavoriteStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Bulk-check favorite status for a set of menu item ids.
   *
   * Accepts a comma-separated list of menu item ids and returns their favorite status in a single request, so menu item cards never issue one favorite-status request each.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerGetMenuItemFavoriteStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerGetMenuItemFavoriteStatus(params: FavoritesControllerGetMenuItemFavoriteStatus$Params, context?: HttpContext): Promise<Array<FavoriteStatusItemDto>> {
    const resp = this.favoritesControllerGetMenuItemFavoriteStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FavoriteStatusItemDto>>): Array<FavoriteStatusItemDto> => r.body);
  }

  /** Path part for operation `favoritesControllerAddMenuItemFavorite()` */
  static readonly FavoritesControllerAddMenuItemFavoritePath = '/api/v1/favorites/menu-items/{menuItemId}';

  /**
   * Add a menu item to favorites.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerAddMenuItemFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerAddMenuItemFavorite$Response(params: FavoritesControllerAddMenuItemFavorite$Params, context?: HttpContext): Promise<StrictHttpResponse<FavoriteToggleResponseDto>> {
    const obs = favoritesControllerAddMenuItemFavorite(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Add a menu item to favorites.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerAddMenuItemFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerAddMenuItemFavorite(params: FavoritesControllerAddMenuItemFavorite$Params, context?: HttpContext): Promise<FavoriteToggleResponseDto> {
    const resp = this.favoritesControllerAddMenuItemFavorite$Response(params, context);
    return resp.then((r: StrictHttpResponse<FavoriteToggleResponseDto>): FavoriteToggleResponseDto => r.body);
  }

  /** Path part for operation `favoritesControllerRemoveMenuItemFavorite()` */
  static readonly FavoritesControllerRemoveMenuItemFavoritePath = '/api/v1/favorites/menu-items/{menuItemId}';

  /**
   * Remove a menu item from favorites.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `favoritesControllerRemoveMenuItemFavorite()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerRemoveMenuItemFavorite$Response(params: FavoritesControllerRemoveMenuItemFavorite$Params, context?: HttpContext): Promise<StrictHttpResponse<FavoriteToggleResponseDto>> {
    const obs = favoritesControllerRemoveMenuItemFavorite(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Remove a menu item from favorites.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `favoritesControllerRemoveMenuItemFavorite$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  favoritesControllerRemoveMenuItemFavorite(params: FavoritesControllerRemoveMenuItemFavorite$Params, context?: HttpContext): Promise<FavoriteToggleResponseDto> {
    const resp = this.favoritesControllerRemoveMenuItemFavorite$Response(params, context);
    return resp.then((r: StrictHttpResponse<FavoriteToggleResponseDto>): FavoriteToggleResponseDto => r.body);
  }

}
