/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { faqControllerCreate } from '../fn/help-center-fa-qs/faq-controller-create';
import { FaqControllerCreate$Params } from '../fn/help-center-fa-qs/faq-controller-create';
import { faqControllerDelete } from '../fn/help-center-fa-qs/faq-controller-delete';
import { FaqControllerDelete$Params } from '../fn/help-center-fa-qs/faq-controller-delete';
import { faqControllerFindActive } from '../fn/help-center-fa-qs/faq-controller-find-active';
import { FaqControllerFindActive$Params } from '../fn/help-center-fa-qs/faq-controller-find-active';
import { faqControllerFindAllForAdmin } from '../fn/help-center-fa-qs/faq-controller-find-all-for-admin';
import { FaqControllerFindAllForAdmin$Params } from '../fn/help-center-fa-qs/faq-controller-find-all-for-admin';
import { faqControllerUpdate } from '../fn/help-center-fa-qs/faq-controller-update';
import { FaqControllerUpdate$Params } from '../fn/help-center-fa-qs/faq-controller-update';
import { FaqResponseDto } from '../models/faq-response-dto';

@Injectable({ providedIn: 'root' })
export class HelpCenterFaQsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `faqControllerFindActive()` */
  static readonly FaqControllerFindActivePath = '/api/v1/faqs';

  /**
   * Get active FAQs, optionally filtered by category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqControllerFindActive()` instead.
   *
   * This method doesn't expect any request body.
   */
  faqControllerFindActive$Response(params?: FaqControllerFindActive$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FaqResponseDto>>> {
    const obs = faqControllerFindActive(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get active FAQs, optionally filtered by category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqControllerFindActive$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  faqControllerFindActive(params?: FaqControllerFindActive$Params, context?: HttpContext): Promise<Array<FaqResponseDto>> {
    const resp = this.faqControllerFindActive$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FaqResponseDto>>): Array<FaqResponseDto> => r.body);
  }

  /** Path part for operation `faqControllerFindAllForAdmin()` */
  static readonly FaqControllerFindAllForAdminPath = '/api/v1/faqs/admin';

  /**
   * Admin — list every FAQ including inactive ones.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqControllerFindAllForAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  faqControllerFindAllForAdmin$Response(params?: FaqControllerFindAllForAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = faqControllerFindAllForAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Admin — list every FAQ including inactive ones.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqControllerFindAllForAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  faqControllerFindAllForAdmin(params?: FaqControllerFindAllForAdmin$Params, context?: HttpContext): Promise<void> {
    const resp = this.faqControllerFindAllForAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `faqControllerCreate()` */
  static readonly FaqControllerCreatePath = '/api/v1/faqs/admin';

  /**
   * Admin — create an FAQ entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqControllerCreate$Response(params: FaqControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = faqControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Admin — create an FAQ entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqControllerCreate(params: FaqControllerCreate$Params, context?: HttpContext): Promise<void> {
    const resp = this.faqControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `faqControllerDelete()` */
  static readonly FaqControllerDeletePath = '/api/v1/faqs/admin/{id}';

  /**
   * Admin — delete an FAQ entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  faqControllerDelete$Response(params: FaqControllerDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = faqControllerDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Admin — delete an FAQ entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  faqControllerDelete(params: FaqControllerDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.faqControllerDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `faqControllerUpdate()` */
  static readonly FaqControllerUpdatePath = '/api/v1/faqs/admin/{id}';

  /**
   * Admin — update an FAQ entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `faqControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqControllerUpdate$Response(params: FaqControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = faqControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Admin — update an FAQ entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `faqControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  faqControllerUpdate(params: FaqControllerUpdate$Params, context?: HttpContext): Promise<void> {
    const resp = this.faqControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
