/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { MenuAddonOptionResponseDto } from '../models/menu-addon-option-response-dto';
import { MenuAddonResponseDto } from '../models/menu-addon-response-dto';
import { MenuCategoryResponseDto } from '../models/menu-category-response-dto';
import { menuControllerCreateAddon } from '../fn/menu/menu-controller-create-addon';
import { MenuControllerCreateAddon$Params } from '../fn/menu/menu-controller-create-addon';
import { menuControllerCreateAddonOption } from '../fn/menu/menu-controller-create-addon-option';
import { MenuControllerCreateAddonOption$Params } from '../fn/menu/menu-controller-create-addon-option';
import { menuControllerCreateCategory } from '../fn/menu/menu-controller-create-category';
import { MenuControllerCreateCategory$Params } from '../fn/menu/menu-controller-create-category';
import { menuControllerCreateMenuItem } from '../fn/menu/menu-controller-create-menu-item';
import { MenuControllerCreateMenuItem$Params } from '../fn/menu/menu-controller-create-menu-item';
import { menuControllerCreateVariant } from '../fn/menu/menu-controller-create-variant';
import { MenuControllerCreateVariant$Params } from '../fn/menu/menu-controller-create-variant';
import { menuControllerDeleteAddon } from '../fn/menu/menu-controller-delete-addon';
import { MenuControllerDeleteAddon$Params } from '../fn/menu/menu-controller-delete-addon';
import { menuControllerDeleteAddonOption } from '../fn/menu/menu-controller-delete-addon-option';
import { MenuControllerDeleteAddonOption$Params } from '../fn/menu/menu-controller-delete-addon-option';
import { menuControllerDeleteCategory } from '../fn/menu/menu-controller-delete-category';
import { MenuControllerDeleteCategory$Params } from '../fn/menu/menu-controller-delete-category';
import { menuControllerDeleteMenuItem } from '../fn/menu/menu-controller-delete-menu-item';
import { MenuControllerDeleteMenuItem$Params } from '../fn/menu/menu-controller-delete-menu-item';
import { menuControllerDeleteVariant } from '../fn/menu/menu-controller-delete-variant';
import { MenuControllerDeleteVariant$Params } from '../fn/menu/menu-controller-delete-variant';
import { menuControllerGetAddonById } from '../fn/menu/menu-controller-get-addon-by-id';
import { MenuControllerGetAddonById$Params } from '../fn/menu/menu-controller-get-addon-by-id';
import { menuControllerGetAddonOptionById } from '../fn/menu/menu-controller-get-addon-option-by-id';
import { MenuControllerGetAddonOptionById$Params } from '../fn/menu/menu-controller-get-addon-option-by-id';
import { menuControllerGetCategoryById } from '../fn/menu/menu-controller-get-category-by-id';
import { MenuControllerGetCategoryById$Params } from '../fn/menu/menu-controller-get-category-by-id';
import { menuControllerGetMenuItemById } from '../fn/menu/menu-controller-get-menu-item-by-id';
import { MenuControllerGetMenuItemById$Params } from '../fn/menu/menu-controller-get-menu-item-by-id';
import { menuControllerGetRestaurantMenu } from '../fn/menu/menu-controller-get-restaurant-menu';
import { MenuControllerGetRestaurantMenu$Params } from '../fn/menu/menu-controller-get-restaurant-menu';
import { menuControllerGetVariantById } from '../fn/menu/menu-controller-get-variant-by-id';
import { MenuControllerGetVariantById$Params } from '../fn/menu/menu-controller-get-variant-by-id';
import { menuControllerToggleAvailability } from '../fn/menu/menu-controller-toggle-availability';
import { MenuControllerToggleAvailability$Params } from '../fn/menu/menu-controller-toggle-availability';
import { menuControllerUpdateAddon } from '../fn/menu/menu-controller-update-addon';
import { MenuControllerUpdateAddon$Params } from '../fn/menu/menu-controller-update-addon';
import { menuControllerUpdateAddonOption } from '../fn/menu/menu-controller-update-addon-option';
import { MenuControllerUpdateAddonOption$Params } from '../fn/menu/menu-controller-update-addon-option';
import { menuControllerUpdateCategory } from '../fn/menu/menu-controller-update-category';
import { MenuControllerUpdateCategory$Params } from '../fn/menu/menu-controller-update-category';
import { menuControllerUpdateMenuItem } from '../fn/menu/menu-controller-update-menu-item';
import { MenuControllerUpdateMenuItem$Params } from '../fn/menu/menu-controller-update-menu-item';
import { menuControllerUpdateVariant } from '../fn/menu/menu-controller-update-variant';
import { MenuControllerUpdateVariant$Params } from '../fn/menu/menu-controller-update-variant';
import { MenuItemResponseDto } from '../models/menu-item-response-dto';
import { MenuItemVariantResponseDto } from '../models/menu-item-variant-response-dto';

@Injectable({ providedIn: 'root' })
export class MenuService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `menuControllerCreateCategory()` */
  static readonly MenuControllerCreateCategoryPath = '/api/v1/menu/categories';

  /**
   * Create menu category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreateCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateCategory$Response(params: MenuControllerCreateCategory$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuCategoryResponseDto>> {
    const obs = menuControllerCreateCategory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create menu category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreateCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateCategory(params: MenuControllerCreateCategory$Params, context?: HttpContext): Promise<MenuCategoryResponseDto> {
    const resp = this.menuControllerCreateCategory$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuCategoryResponseDto>): MenuCategoryResponseDto => r.body);
  }

  /** Path part for operation `menuControllerCreateMenuItem()` */
  static readonly MenuControllerCreateMenuItemPath = '/api/v1/menu/items';

  /**
   * Create menu item.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreateMenuItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateMenuItem$Response(params: MenuControllerCreateMenuItem$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemResponseDto>> {
    const obs = menuControllerCreateMenuItem(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create menu item.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreateMenuItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateMenuItem(params: MenuControllerCreateMenuItem$Params, context?: HttpContext): Promise<MenuItemResponseDto> {
    const resp = this.menuControllerCreateMenuItem$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemResponseDto>): MenuItemResponseDto => r.body);
  }

  /** Path part for operation `menuControllerGetMenuItemById()` */
  static readonly MenuControllerGetMenuItemByIdPath = '/api/v1/menu/items/{id}';

  /**
   * Get menu item by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerGetMenuItemById()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetMenuItemById$Response(params: MenuControllerGetMenuItemById$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemResponseDto>> {
    const obs = menuControllerGetMenuItemById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get menu item by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerGetMenuItemById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetMenuItemById(params: MenuControllerGetMenuItemById$Params, context?: HttpContext): Promise<MenuItemResponseDto> {
    const resp = this.menuControllerGetMenuItemById$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemResponseDto>): MenuItemResponseDto => r.body);
  }

  /** Path part for operation `menuControllerDeleteMenuItem()` */
  static readonly MenuControllerDeleteMenuItemPath = '/api/v1/menu/items/{id}';

  /**
   * Delete menu item.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDeleteMenuItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteMenuItem$Response(params: MenuControllerDeleteMenuItem$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = menuControllerDeleteMenuItem(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete menu item.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDeleteMenuItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteMenuItem(params: MenuControllerDeleteMenuItem$Params, context?: HttpContext): Promise<void> {
    const resp = this.menuControllerDeleteMenuItem$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `menuControllerUpdateMenuItem()` */
  static readonly MenuControllerUpdateMenuItemPath = '/api/v1/menu/items/{id}';

  /**
   * Update menu item.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdateMenuItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateMenuItem$Response(params: MenuControllerUpdateMenuItem$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemResponseDto>> {
    const obs = menuControllerUpdateMenuItem(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update menu item.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdateMenuItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateMenuItem(params: MenuControllerUpdateMenuItem$Params, context?: HttpContext): Promise<MenuItemResponseDto> {
    const resp = this.menuControllerUpdateMenuItem$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemResponseDto>): MenuItemResponseDto => r.body);
  }

  /** Path part for operation `menuControllerToggleAvailability()` */
  static readonly MenuControllerToggleAvailabilityPath = '/api/v1/menu/items/{id}/availability';

  /**
   * Toggle menu item availability.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerToggleAvailability()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerToggleAvailability$Response(params: MenuControllerToggleAvailability$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemResponseDto>> {
    const obs = menuControllerToggleAvailability(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Toggle menu item availability.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerToggleAvailability$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerToggleAvailability(params: MenuControllerToggleAvailability$Params, context?: HttpContext): Promise<MenuItemResponseDto> {
    const resp = this.menuControllerToggleAvailability$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemResponseDto>): MenuItemResponseDto => r.body);
  }

  /** Path part for operation `menuControllerGetCategoryById()` */
  static readonly MenuControllerGetCategoryByIdPath = '/api/v1/menu/categories/{id}';

  /**
   * Get category by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerGetCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetCategoryById$Response(params: MenuControllerGetCategoryById$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuCategoryResponseDto>> {
    const obs = menuControllerGetCategoryById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get category by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerGetCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetCategoryById(params: MenuControllerGetCategoryById$Params, context?: HttpContext): Promise<MenuCategoryResponseDto> {
    const resp = this.menuControllerGetCategoryById$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuCategoryResponseDto>): MenuCategoryResponseDto => r.body);
  }

  /** Path part for operation `menuControllerDeleteCategory()` */
  static readonly MenuControllerDeleteCategoryPath = '/api/v1/menu/categories/{id}';

  /**
   * Delete category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDeleteCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteCategory$Response(params: MenuControllerDeleteCategory$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = menuControllerDeleteCategory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDeleteCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteCategory(params: MenuControllerDeleteCategory$Params, context?: HttpContext): Promise<void> {
    const resp = this.menuControllerDeleteCategory$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `menuControllerUpdateCategory()` */
  static readonly MenuControllerUpdateCategoryPath = '/api/v1/menu/categories/{id}';

  /**
   * Update category.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdateCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateCategory$Response(params: MenuControllerUpdateCategory$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuCategoryResponseDto>> {
    const obs = menuControllerUpdateCategory(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update category.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdateCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateCategory(params: MenuControllerUpdateCategory$Params, context?: HttpContext): Promise<MenuCategoryResponseDto> {
    const resp = this.menuControllerUpdateCategory$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuCategoryResponseDto>): MenuCategoryResponseDto => r.body);
  }

  /** Path part for operation `menuControllerCreateVariant()` */
  static readonly MenuControllerCreateVariantPath = '/api/v1/menu/items/{id}/variants';

  /**
   * Create menu item variant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreateVariant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateVariant$Response(params: MenuControllerCreateVariant$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemVariantResponseDto>> {
    const obs = menuControllerCreateVariant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create menu item variant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreateVariant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateVariant(params: MenuControllerCreateVariant$Params, context?: HttpContext): Promise<MenuItemVariantResponseDto> {
    const resp = this.menuControllerCreateVariant$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemVariantResponseDto>): MenuItemVariantResponseDto => r.body);
  }

  /** Path part for operation `menuControllerGetVariantById()` */
  static readonly MenuControllerGetVariantByIdPath = '/api/v1/menu/variants/{id}';

  /**
   * Get variant by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerGetVariantById()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetVariantById$Response(params: MenuControllerGetVariantById$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemVariantResponseDto>> {
    const obs = menuControllerGetVariantById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get variant by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerGetVariantById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetVariantById(params: MenuControllerGetVariantById$Params, context?: HttpContext): Promise<MenuItemVariantResponseDto> {
    const resp = this.menuControllerGetVariantById$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemVariantResponseDto>): MenuItemVariantResponseDto => r.body);
  }

  /** Path part for operation `menuControllerDeleteVariant()` */
  static readonly MenuControllerDeleteVariantPath = '/api/v1/menu/variants/{id}';

  /**
   * Delete variant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDeleteVariant()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteVariant$Response(params: MenuControllerDeleteVariant$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = menuControllerDeleteVariant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete variant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDeleteVariant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteVariant(params: MenuControllerDeleteVariant$Params, context?: HttpContext): Promise<void> {
    const resp = this.menuControllerDeleteVariant$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `menuControllerUpdateVariant()` */
  static readonly MenuControllerUpdateVariantPath = '/api/v1/menu/variants/{id}';

  /**
   * Update variant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdateVariant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateVariant$Response(params: MenuControllerUpdateVariant$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuItemVariantResponseDto>> {
    const obs = menuControllerUpdateVariant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update variant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdateVariant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateVariant(params: MenuControllerUpdateVariant$Params, context?: HttpContext): Promise<MenuItemVariantResponseDto> {
    const resp = this.menuControllerUpdateVariant$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuItemVariantResponseDto>): MenuItemVariantResponseDto => r.body);
  }

  /** Path part for operation `menuControllerCreateAddon()` */
  static readonly MenuControllerCreateAddonPath = '/api/v1/menu/items/{id}/addons';

  /**
   * Create addon group.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreateAddon()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateAddon$Response(params: MenuControllerCreateAddon$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuAddonResponseDto>> {
    const obs = menuControllerCreateAddon(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create addon group.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreateAddon$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateAddon(params: MenuControllerCreateAddon$Params, context?: HttpContext): Promise<MenuAddonResponseDto> {
    const resp = this.menuControllerCreateAddon$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuAddonResponseDto>): MenuAddonResponseDto => r.body);
  }

  /** Path part for operation `menuControllerGetAddonById()` */
  static readonly MenuControllerGetAddonByIdPath = '/api/v1/menu/addons/{id}';

  /**
   * Get addon by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerGetAddonById()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetAddonById$Response(params: MenuControllerGetAddonById$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuAddonResponseDto>> {
    const obs = menuControllerGetAddonById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get addon by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerGetAddonById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetAddonById(params: MenuControllerGetAddonById$Params, context?: HttpContext): Promise<MenuAddonResponseDto> {
    const resp = this.menuControllerGetAddonById$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuAddonResponseDto>): MenuAddonResponseDto => r.body);
  }

  /** Path part for operation `menuControllerDeleteAddon()` */
  static readonly MenuControllerDeleteAddonPath = '/api/v1/menu/addons/{id}';

  /**
   * Delete addon.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDeleteAddon()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteAddon$Response(params: MenuControllerDeleteAddon$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = menuControllerDeleteAddon(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete addon.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDeleteAddon$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteAddon(params: MenuControllerDeleteAddon$Params, context?: HttpContext): Promise<void> {
    const resp = this.menuControllerDeleteAddon$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `menuControllerUpdateAddon()` */
  static readonly MenuControllerUpdateAddonPath = '/api/v1/menu/addons/{id}';

  /**
   * Update addon.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdateAddon()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateAddon$Response(params: MenuControllerUpdateAddon$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuAddonResponseDto>> {
    const obs = menuControllerUpdateAddon(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update addon.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdateAddon$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateAddon(params: MenuControllerUpdateAddon$Params, context?: HttpContext): Promise<MenuAddonResponseDto> {
    const resp = this.menuControllerUpdateAddon$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuAddonResponseDto>): MenuAddonResponseDto => r.body);
  }

  /** Path part for operation `menuControllerCreateAddonOption()` */
  static readonly MenuControllerCreateAddonOptionPath = '/api/v1/menu/addons/{id}/options';

  /**
   * Create addon option.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreateAddonOption()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateAddonOption$Response(params: MenuControllerCreateAddonOption$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuAddonOptionResponseDto>> {
    const obs = menuControllerCreateAddonOption(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create addon option.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreateAddonOption$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreateAddonOption(params: MenuControllerCreateAddonOption$Params, context?: HttpContext): Promise<MenuAddonOptionResponseDto> {
    const resp = this.menuControllerCreateAddonOption$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuAddonOptionResponseDto>): MenuAddonOptionResponseDto => r.body);
  }

  /** Path part for operation `menuControllerGetAddonOptionById()` */
  static readonly MenuControllerGetAddonOptionByIdPath = '/api/v1/menu/options/{id}';

  /**
   * Get addon option by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerGetAddonOptionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetAddonOptionById$Response(params: MenuControllerGetAddonOptionById$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuAddonOptionResponseDto>> {
    const obs = menuControllerGetAddonOptionById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get addon option by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerGetAddonOptionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetAddonOptionById(params: MenuControllerGetAddonOptionById$Params, context?: HttpContext): Promise<MenuAddonOptionResponseDto> {
    const resp = this.menuControllerGetAddonOptionById$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuAddonOptionResponseDto>): MenuAddonOptionResponseDto => r.body);
  }

  /** Path part for operation `menuControllerDeleteAddonOption()` */
  static readonly MenuControllerDeleteAddonOptionPath = '/api/v1/menu/options/{id}';

  /**
   * Delete addon option.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDeleteAddonOption()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteAddonOption$Response(params: MenuControllerDeleteAddonOption$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = menuControllerDeleteAddonOption(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete addon option.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDeleteAddonOption$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeleteAddonOption(params: MenuControllerDeleteAddonOption$Params, context?: HttpContext): Promise<void> {
    const resp = this.menuControllerDeleteAddonOption$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `menuControllerUpdateAddonOption()` */
  static readonly MenuControllerUpdateAddonOptionPath = '/api/v1/menu/options/{id}';

  /**
   * Update addon option.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdateAddonOption()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateAddonOption$Response(params: MenuControllerUpdateAddonOption$Params, context?: HttpContext): Promise<StrictHttpResponse<MenuAddonOptionResponseDto>> {
    const obs = menuControllerUpdateAddonOption(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update addon option.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdateAddonOption$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdateAddonOption(params: MenuControllerUpdateAddonOption$Params, context?: HttpContext): Promise<MenuAddonOptionResponseDto> {
    const resp = this.menuControllerUpdateAddonOption$Response(params, context);
    return resp.then((r: StrictHttpResponse<MenuAddonOptionResponseDto>): MenuAddonOptionResponseDto => r.body);
  }

  /** Path part for operation `menuControllerGetRestaurantMenu()` */
  static readonly MenuControllerGetRestaurantMenuPath = '/api/v1/menu/{restaurantId}';

  /**
   * Get complete restaurant menu.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerGetRestaurantMenu()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetRestaurantMenu$Response(params: MenuControllerGetRestaurantMenu$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<MenuCategoryResponseDto>>> {
    const obs = menuControllerGetRestaurantMenu(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get complete restaurant menu.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerGetRestaurantMenu$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerGetRestaurantMenu(params: MenuControllerGetRestaurantMenu$Params, context?: HttpContext): Promise<Array<MenuCategoryResponseDto>> {
    const resp = this.menuControllerGetRestaurantMenu$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<MenuCategoryResponseDto>>): Array<MenuCategoryResponseDto> => r.body);
  }

}
