/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { metricsControllerGetMetrics } from '../fn/metrics/metrics-controller-get-metrics';
import { MetricsControllerGetMetrics$Params } from '../fn/metrics/metrics-controller-get-metrics';

@Injectable({ providedIn: 'root' })
export class MetricsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `metricsControllerGetMetrics()` */
  static readonly MetricsControllerGetMetricsPath = '/metrics';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `metricsControllerGetMetrics()` instead.
   *
   * This method doesn't expect any request body.
   */
  metricsControllerGetMetrics$Response(params?: MetricsControllerGetMetrics$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = metricsControllerGetMetrics(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `metricsControllerGetMetrics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  metricsControllerGetMetrics(params?: MetricsControllerGetMetrics$Params, context?: HttpContext): Promise<void> {
    const resp = this.metricsControllerGetMetrics$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
