/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { NotificationResponseDto } from '../models/notification-response-dto';
import { notificationsControllerGetMyNotifications } from '../fn/notifications/notifications-controller-get-my-notifications';
import { NotificationsControllerGetMyNotifications$Params } from '../fn/notifications/notifications-controller-get-my-notifications';
import { notificationsControllerMarkAsRead } from '../fn/notifications/notifications-controller-mark-as-read';
import { NotificationsControllerMarkAsRead$Params } from '../fn/notifications/notifications-controller-mark-as-read';
import { notificationsControllerRegisterPushToken } from '../fn/notifications/notifications-controller-register-push-token';
import { NotificationsControllerRegisterPushToken$Params } from '../fn/notifications/notifications-controller-register-push-token';
import { PushTokenResponseDto } from '../models/push-token-response-dto';

@Injectable({ providedIn: 'root' })
export class NotificationsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `notificationsControllerGetMyNotifications()` */
  static readonly NotificationsControllerGetMyNotificationsPath = '/api/v1/notifications/me';

  /**
   * Get my notifications.
   *
   * Returns notifications belonging to the authenticated user.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerGetMyNotifications()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerGetMyNotifications$Response(params?: NotificationsControllerGetMyNotifications$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<NotificationResponseDto>>> {
    const obs = notificationsControllerGetMyNotifications(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get my notifications.
   *
   * Returns notifications belonging to the authenticated user.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerGetMyNotifications$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerGetMyNotifications(params?: NotificationsControllerGetMyNotifications$Params, context?: HttpContext): Promise<Array<NotificationResponseDto>> {
    const resp = this.notificationsControllerGetMyNotifications$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<NotificationResponseDto>>): Array<NotificationResponseDto> => r.body);
  }

  /** Path part for operation `notificationsControllerMarkAsRead()` */
  static readonly NotificationsControllerMarkAsReadPath = '/api/v1/notifications/{id}/read';

  /**
   * Mark notification as read.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerMarkAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerMarkAsRead$Response(params: NotificationsControllerMarkAsRead$Params, context?: HttpContext): Promise<StrictHttpResponse<NotificationResponseDto>> {
    const obs = notificationsControllerMarkAsRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Mark notification as read.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerMarkAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  notificationsControllerMarkAsRead(params: NotificationsControllerMarkAsRead$Params, context?: HttpContext): Promise<NotificationResponseDto> {
    const resp = this.notificationsControllerMarkAsRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<NotificationResponseDto>): NotificationResponseDto => r.body);
  }

  /** Path part for operation `notificationsControllerRegisterPushToken()` */
  static readonly NotificationsControllerRegisterPushTokenPath = '/api/v1/notifications/push-token';

  /**
   * Register push notification token.
   *
   * Register a device push token for receiving notifications.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `notificationsControllerRegisterPushToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerRegisterPushToken$Response(params: NotificationsControllerRegisterPushToken$Params, context?: HttpContext): Promise<StrictHttpResponse<PushTokenResponseDto>> {
    const obs = notificationsControllerRegisterPushToken(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Register push notification token.
   *
   * Register a device push token for receiving notifications.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `notificationsControllerRegisterPushToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  notificationsControllerRegisterPushToken(params: NotificationsControllerRegisterPushToken$Params, context?: HttpContext): Promise<PushTokenResponseDto> {
    const resp = this.notificationsControllerRegisterPushToken$Response(params, context);
    return resp.then((r: StrictHttpResponse<PushTokenResponseDto>): PushTokenResponseDto => r.body);
  }

}
