/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OfferResponseDto } from '../models/offer-response-dto';
import { offersControllerFindAll } from '../fn/offers/offers-controller-find-all';
import { OffersControllerFindAll$Params } from '../fn/offers/offers-controller-find-all';
import { offersControllerFindById } from '../fn/offers/offers-controller-find-by-id';
import { OffersControllerFindById$Params } from '../fn/offers/offers-controller-find-by-id';
import { offersControllerFindByRestaurant } from '../fn/offers/offers-controller-find-by-restaurant';
import { OffersControllerFindByRestaurant$Params } from '../fn/offers/offers-controller-find-by-restaurant';
import { offersControllerFindFeatured } from '../fn/offers/offers-controller-find-featured';
import { OffersControllerFindFeatured$Params } from '../fn/offers/offers-controller-find-featured';
import { offersControllerFindHome } from '../fn/offers/offers-controller-find-home';
import { OffersControllerFindHome$Params } from '../fn/offers/offers-controller-find-home';
import { PaginatedOffersResponseDto } from '../models/paginated-offers-response-dto';

@Injectable({ providedIn: 'root' })
export class OffersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `offersControllerFindAll()` */
  static readonly OffersControllerFindAllPath = '/api/v1/offers';

  /**
   * List active offers.
   *
   * Paginated, searchable, filterable list of currently active offers (isActive and within their start/end window).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `offersControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindAll$Response(params?: OffersControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedOffersResponseDto>> {
    const obs = offersControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List active offers.
   *
   * Paginated, searchable, filterable list of currently active offers (isActive and within their start/end window).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `offersControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindAll(params?: OffersControllerFindAll$Params, context?: HttpContext): Promise<PaginatedOffersResponseDto> {
    const resp = this.offersControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedOffersResponseDto>): PaginatedOffersResponseDto => r.body);
  }

  /** Path part for operation `offersControllerFindFeatured()` */
  static readonly OffersControllerFindFeaturedPath = '/api/v1/offers/featured';

  /**
   * Get featured offers.
   *
   * A short, non-paginated list of active offers, newest first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `offersControllerFindFeatured()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindFeatured$Response(params?: OffersControllerFindFeatured$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<OfferResponseDto>>> {
    const obs = offersControllerFindFeatured(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get featured offers.
   *
   * A short, non-paginated list of active offers, newest first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `offersControllerFindFeatured$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindFeatured(params?: OffersControllerFindFeatured$Params, context?: HttpContext): Promise<Array<OfferResponseDto>> {
    const resp = this.offersControllerFindFeatured$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<OfferResponseDto>>): Array<OfferResponseDto> => r.body);
  }

  /** Path part for operation `offersControllerFindHome()` */
  static readonly OffersControllerFindHomePath = '/api/v1/offers/home';

  /**
   * Get the offers shown on the customer home banners.
   *
   * Same active-offer criteria as /offers/featured — exposed separately so the home page banner carousel can be fetched on its own.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `offersControllerFindHome()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindHome$Response(params?: OffersControllerFindHome$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<OfferResponseDto>>> {
    const obs = offersControllerFindHome(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get the offers shown on the customer home banners.
   *
   * Same active-offer criteria as /offers/featured — exposed separately so the home page banner carousel can be fetched on its own.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `offersControllerFindHome$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindHome(params?: OffersControllerFindHome$Params, context?: HttpContext): Promise<Array<OfferResponseDto>> {
    const resp = this.offersControllerFindHome$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<OfferResponseDto>>): Array<OfferResponseDto> => r.body);
  }

  /** Path part for operation `offersControllerFindByRestaurant()` */
  static readonly OffersControllerFindByRestaurantPath = '/api/v1/offers/restaurants/{restaurantId}';

  /**
   * Get a restaurant's active offers.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `offersControllerFindByRestaurant()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindByRestaurant$Response(params: OffersControllerFindByRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedOffersResponseDto>> {
    const obs = offersControllerFindByRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get a restaurant's active offers.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `offersControllerFindByRestaurant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindByRestaurant(params: OffersControllerFindByRestaurant$Params, context?: HttpContext): Promise<PaginatedOffersResponseDto> {
    const resp = this.offersControllerFindByRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedOffersResponseDto>): PaginatedOffersResponseDto => r.body);
  }

  /** Path part for operation `offersControllerFindById()` */
  static readonly OffersControllerFindByIdPath = '/api/v1/offers/{id}';

  /**
   * Get offer details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `offersControllerFindById()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindById$Response(params: OffersControllerFindById$Params, context?: HttpContext): Promise<StrictHttpResponse<OfferResponseDto>> {
    const obs = offersControllerFindById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get offer details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `offersControllerFindById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  offersControllerFindById(params: OffersControllerFindById$Params, context?: HttpContext): Promise<OfferResponseDto> {
    const resp = this.offersControllerFindById$Response(params, context);
    return resp.then((r: StrictHttpResponse<OfferResponseDto>): OfferResponseDto => r.body);
  }

}
