/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { verificationControllerAdvance } from '../fn/restaurant-verification/verification-controller-advance';
import { VerificationControllerAdvance$Params } from '../fn/restaurant-verification/verification-controller-advance';
import { verificationControllerGetStatus } from '../fn/restaurant-verification/verification-controller-get-status';
import { VerificationControllerGetStatus$Params } from '../fn/restaurant-verification/verification-controller-get-status';
import { verificationControllerReinstate } from '../fn/restaurant-verification/verification-controller-reinstate';
import { VerificationControllerReinstate$Params } from '../fn/restaurant-verification/verification-controller-reinstate';
import { verificationControllerReject } from '../fn/restaurant-verification/verification-controller-reject';
import { VerificationControllerReject$Params } from '../fn/restaurant-verification/verification-controller-reject';
import { verificationControllerSubmit } from '../fn/restaurant-verification/verification-controller-submit';
import { VerificationControllerSubmit$Params } from '../fn/restaurant-verification/verification-controller-submit';
import { verificationControllerSuspend } from '../fn/restaurant-verification/verification-controller-suspend';
import { VerificationControllerSuspend$Params } from '../fn/restaurant-verification/verification-controller-suspend';
import { VerificationResponseDto } from '../models/verification-response-dto';

@Injectable({ providedIn: 'root' })
export class RestaurantVerificationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `verificationControllerGetStatus()` */
  static readonly VerificationControllerGetStatusPath = '/api/v1/restaurants/{restaurantId}/verification';

  /**
   * Get verification status.
   *
   * Dedicated aggregate, separate from the coarse Restaurant.status enum — see stage for the detailed onboarding step.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationControllerGetStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerGetStatus$Response(params: VerificationControllerGetStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationResponseDto>> {
    const obs = verificationControllerGetStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get verification status.
   *
   * Dedicated aggregate, separate from the coarse Restaurant.status enum — see stage for the detailed onboarding step.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationControllerGetStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerGetStatus(params: VerificationControllerGetStatus$Params, context?: HttpContext): Promise<VerificationResponseDto> {
    const resp = this.verificationControllerGetStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationResponseDto>): VerificationResponseDto => r.body);
  }

  /** Path part for operation `verificationControllerSubmit()` */
  static readonly VerificationControllerSubmitPath = '/api/v1/restaurants/{restaurantId}/verification/submit';

  /**
   * Submit for verification (DRAFT -> SUBMITTED).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationControllerSubmit()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerSubmit$Response(params: VerificationControllerSubmit$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationResponseDto>> {
    const obs = verificationControllerSubmit(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Submit for verification (DRAFT -> SUBMITTED).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationControllerSubmit$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerSubmit(params: VerificationControllerSubmit$Params, context?: HttpContext): Promise<VerificationResponseDto> {
    const resp = this.verificationControllerSubmit$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationResponseDto>): VerificationResponseDto => r.body);
  }

  /** Path part for operation `verificationControllerAdvance()` */
  static readonly VerificationControllerAdvancePath = '/api/v1/restaurants/{restaurantId}/verification/advance';

  /**
   * Advance to the next verification stage (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationControllerAdvance()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerAdvance$Response(params: VerificationControllerAdvance$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationResponseDto>> {
    const obs = verificationControllerAdvance(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Advance to the next verification stage (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationControllerAdvance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerAdvance(params: VerificationControllerAdvance$Params, context?: HttpContext): Promise<VerificationResponseDto> {
    const resp = this.verificationControllerAdvance$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationResponseDto>): VerificationResponseDto => r.body);
  }

  /** Path part for operation `verificationControllerReject()` */
  static readonly VerificationControllerRejectPath = '/api/v1/restaurants/{restaurantId}/verification/reject';

  /**
   * Reject verification (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationControllerReject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificationControllerReject$Response(params: VerificationControllerReject$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationResponseDto>> {
    const obs = verificationControllerReject(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Reject verification (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationControllerReject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificationControllerReject(params: VerificationControllerReject$Params, context?: HttpContext): Promise<VerificationResponseDto> {
    const resp = this.verificationControllerReject$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationResponseDto>): VerificationResponseDto => r.body);
  }

  /** Path part for operation `verificationControllerSuspend()` */
  static readonly VerificationControllerSuspendPath = '/api/v1/restaurants/{restaurantId}/verification/suspend';

  /**
   * Suspend an approved verification (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationControllerSuspend()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerSuspend$Response(params: VerificationControllerSuspend$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationResponseDto>> {
    const obs = verificationControllerSuspend(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Suspend an approved verification (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationControllerSuspend$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerSuspend(params: VerificationControllerSuspend$Params, context?: HttpContext): Promise<VerificationResponseDto> {
    const resp = this.verificationControllerSuspend$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationResponseDto>): VerificationResponseDto => r.body);
  }

  /** Path part for operation `verificationControllerReinstate()` */
  static readonly VerificationControllerReinstatePath = '/api/v1/restaurants/{restaurantId}/verification/reinstate';

  /**
   * Reinstate a suspended verification (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificationControllerReinstate()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerReinstate$Response(params: VerificationControllerReinstate$Params, context?: HttpContext): Promise<StrictHttpResponse<VerificationResponseDto>> {
    const obs = verificationControllerReinstate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Reinstate a suspended verification (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificationControllerReinstate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificationControllerReinstate(params: VerificationControllerReinstate$Params, context?: HttpContext): Promise<VerificationResponseDto> {
    const resp = this.verificationControllerReinstate$Response(params, context);
    return resp.then((r: StrictHttpResponse<VerificationResponseDto>): VerificationResponseDto => r.body);
  }

}
