/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedRestaurantsResponseDto } from '../models/paginated-restaurants-response-dto';
import { RestaurantResponseDto } from '../models/restaurant-response-dto';
import { restaurantsControllerCreateRestaurant } from '../fn/restaurants/restaurants-controller-create-restaurant';
import { RestaurantsControllerCreateRestaurant$Params } from '../fn/restaurants/restaurants-controller-create-restaurant';
import { restaurantsControllerFindAll } from '../fn/restaurants/restaurants-controller-find-all';
import { RestaurantsControllerFindAll$Params } from '../fn/restaurants/restaurants-controller-find-all';
import { restaurantsControllerGetMyRestaurants } from '../fn/restaurants/restaurants-controller-get-my-restaurants';
import { RestaurantsControllerGetMyRestaurants$Params } from '../fn/restaurants/restaurants-controller-get-my-restaurants';
import { restaurantsControllerGetRestaurantById } from '../fn/restaurants/restaurants-controller-get-restaurant-by-id';
import { RestaurantsControllerGetRestaurantById$Params } from '../fn/restaurants/restaurants-controller-get-restaurant-by-id';

@Injectable({ providedIn: 'root' })
export class RestaurantsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `restaurantsControllerFindAll()` */
  static readonly RestaurantsControllerFindAllPath = '/api/v1/restaurants';

  /**
   * Get restaurants.
   *
   * Returns a paginated list of restaurants available to customers.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerFindAll$Response(params?: RestaurantsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedRestaurantsResponseDto>> {
    const obs = restaurantsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurants.
   *
   * Returns a paginated list of restaurants available to customers.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerFindAll(params?: RestaurantsControllerFindAll$Params, context?: HttpContext): Promise<PaginatedRestaurantsResponseDto> {
    const resp = this.restaurantsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedRestaurantsResponseDto>): PaginatedRestaurantsResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerCreateRestaurant()` */
  static readonly RestaurantsControllerCreateRestaurantPath = '/api/v1/restaurants';

  /**
   * Create restaurant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerCreateRestaurant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  restaurantsControllerCreateRestaurant$Response(params: RestaurantsControllerCreateRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerCreateRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create restaurant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerCreateRestaurant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  restaurantsControllerCreateRestaurant(params: RestaurantsControllerCreateRestaurant$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerCreateRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerGetMyRestaurants()` */
  static readonly RestaurantsControllerGetMyRestaurantsPath = '/api/v1/restaurants/me';

  /**
   * Get restaurants owned by current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerGetMyRestaurants()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetMyRestaurants$Response(params?: RestaurantsControllerGetMyRestaurants$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RestaurantResponseDto>>> {
    const obs = restaurantsControllerGetMyRestaurants(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurants owned by current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerGetMyRestaurants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetMyRestaurants(params?: RestaurantsControllerGetMyRestaurants$Params, context?: HttpContext): Promise<Array<RestaurantResponseDto>> {
    const resp = this.restaurantsControllerGetMyRestaurants$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RestaurantResponseDto>>): Array<RestaurantResponseDto> => r.body);
  }

  /** Path part for operation `restaurantsControllerGetRestaurantById()` */
  static readonly RestaurantsControllerGetRestaurantByIdPath = '/api/v1/restaurants/{id}';

  /**
   * Get restaurant by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerGetRestaurantById()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetRestaurantById$Response(params: RestaurantsControllerGetRestaurantById$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerGetRestaurantById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurant by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerGetRestaurantById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetRestaurantById(params: RestaurantsControllerGetRestaurantById$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerGetRestaurantById$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

}
