/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { onboardingControllerCompleteStep } from '../fn/restaurant-onboarding/onboarding-controller-complete-step';
import { OnboardingControllerCompleteStep$Params } from '../fn/restaurant-onboarding/onboarding-controller-complete-step';
import { onboardingControllerGetState } from '../fn/restaurant-onboarding/onboarding-controller-get-state';
import { OnboardingControllerGetState$Params } from '../fn/restaurant-onboarding/onboarding-controller-get-state';
import { onboardingControllerRequestChanges } from '../fn/restaurant-onboarding/onboarding-controller-request-changes';
import { OnboardingControllerRequestChanges$Params } from '../fn/restaurant-onboarding/onboarding-controller-request-changes';
import { onboardingControllerSubmit } from '../fn/restaurant-onboarding/onboarding-controller-submit';
import { OnboardingControllerSubmit$Params } from '../fn/restaurant-onboarding/onboarding-controller-submit';
import { OnboardingResponseDto } from '../models/onboarding-response-dto';

@Injectable({ providedIn: 'root' })
export class RestaurantOnboardingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `onboardingControllerGetState()` */
  static readonly OnboardingControllerGetStatePath = '/api/v1/restaurants/{restaurantId}/onboarding';

  /**
   * Get onboarding progress.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onboardingControllerGetState()` instead.
   *
   * This method doesn't expect any request body.
   */
  onboardingControllerGetState$Response(params: OnboardingControllerGetState$Params, context?: HttpContext): Promise<StrictHttpResponse<OnboardingResponseDto>> {
    const obs = onboardingControllerGetState(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get onboarding progress.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onboardingControllerGetState$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  onboardingControllerGetState(params: OnboardingControllerGetState$Params, context?: HttpContext): Promise<OnboardingResponseDto> {
    const resp = this.onboardingControllerGetState$Response(params, context);
    return resp.then((r: StrictHttpResponse<OnboardingResponseDto>): OnboardingResponseDto => r.body);
  }

  /** Path part for operation `onboardingControllerCompleteStep()` */
  static readonly OnboardingControllerCompleteStepPath = '/api/v1/restaurants/{restaurantId}/onboarding/steps/{step}';

  /**
   * Mark a wizard step complete.
   *
   * Records wizard progress only — the step's actual data is saved via the existing dedicated endpoint for that section (restaurant profile, branches, tax profile, etc.) before this is called.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onboardingControllerCompleteStep()` instead.
   *
   * This method doesn't expect any request body.
   */
  onboardingControllerCompleteStep$Response(params: OnboardingControllerCompleteStep$Params, context?: HttpContext): Promise<StrictHttpResponse<OnboardingResponseDto>> {
    const obs = onboardingControllerCompleteStep(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Mark a wizard step complete.
   *
   * Records wizard progress only — the step's actual data is saved via the existing dedicated endpoint for that section (restaurant profile, branches, tax profile, etc.) before this is called.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onboardingControllerCompleteStep$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  onboardingControllerCompleteStep(params: OnboardingControllerCompleteStep$Params, context?: HttpContext): Promise<OnboardingResponseDto> {
    const resp = this.onboardingControllerCompleteStep$Response(params, context);
    return resp.then((r: StrictHttpResponse<OnboardingResponseDto>): OnboardingResponseDto => r.body);
  }

  /** Path part for operation `onboardingControllerSubmit()` */
  static readonly OnboardingControllerSubmitPath = '/api/v1/restaurants/{restaurantId}/onboarding/submit';

  /**
   * Submit the onboarding application for review.
   *
   * Requires steps 1-11 complete and acceptedTerms=true. Delegates to the existing verification submit flow.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onboardingControllerSubmit()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onboardingControllerSubmit$Response(params: OnboardingControllerSubmit$Params, context?: HttpContext): Promise<StrictHttpResponse<OnboardingResponseDto>> {
    const obs = onboardingControllerSubmit(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Submit the onboarding application for review.
   *
   * Requires steps 1-11 complete and acceptedTerms=true. Delegates to the existing verification submit flow.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onboardingControllerSubmit$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onboardingControllerSubmit(params: OnboardingControllerSubmit$Params, context?: HttpContext): Promise<OnboardingResponseDto> {
    const resp = this.onboardingControllerSubmit$Response(params, context);
    return resp.then((r: StrictHttpResponse<OnboardingResponseDto>): OnboardingResponseDto => r.body);
  }

  /** Path part for operation `onboardingControllerRequestChanges()` */
  static readonly OnboardingControllerRequestChangesPath = '/api/v1/restaurants/{restaurantId}/onboarding/request-changes';

  /**
   * Request corrections from the restaurant owner (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `onboardingControllerRequestChanges()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onboardingControllerRequestChanges$Response(params: OnboardingControllerRequestChanges$Params, context?: HttpContext): Promise<StrictHttpResponse<OnboardingResponseDto>> {
    const obs = onboardingControllerRequestChanges(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Request corrections from the restaurant owner (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `onboardingControllerRequestChanges$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  onboardingControllerRequestChanges(params: OnboardingControllerRequestChanges$Params, context?: HttpContext): Promise<OnboardingResponseDto> {
    const resp = this.onboardingControllerRequestChanges$Response(params, context);
    return resp.then((r: StrictHttpResponse<OnboardingResponseDto>): OnboardingResponseDto => r.body);
  }

}
