/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ReportResponseDto } from '../models/report-response-dto';
import { reportsControllerCancelledOrders } from '../fn/restaurant-reports/reports-controller-cancelled-orders';
import { ReportsControllerCancelledOrders$Params } from '../fn/restaurant-reports/reports-controller-cancelled-orders';
import { reportsControllerDailySales } from '../fn/restaurant-reports/reports-controller-daily-sales';
import { ReportsControllerDailySales$Params } from '../fn/restaurant-reports/reports-controller-daily-sales';
import { reportsControllerOrders } from '../fn/restaurant-reports/reports-controller-orders';
import { ReportsControllerOrders$Params } from '../fn/restaurant-reports/reports-controller-orders';
import { reportsControllerPaymentSummary } from '../fn/restaurant-reports/reports-controller-payment-summary';
import { ReportsControllerPaymentSummary$Params } from '../fn/restaurant-reports/reports-controller-payment-summary';
import { reportsControllerRefundSummary } from '../fn/restaurant-reports/reports-controller-refund-summary';
import { ReportsControllerRefundSummary$Params } from '../fn/restaurant-reports/reports-controller-refund-summary';
import { reportsControllerRevenue } from '../fn/restaurant-reports/reports-controller-revenue';
import { ReportsControllerRevenue$Params } from '../fn/restaurant-reports/reports-controller-revenue';
import { reportsControllerTaxSummary } from '../fn/restaurant-reports/reports-controller-tax-summary';
import { ReportsControllerTaxSummary$Params } from '../fn/restaurant-reports/reports-controller-tax-summary';

@Injectable({ providedIn: 'root' })
export class RestaurantReportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `reportsControllerDailySales()` */
  static readonly ReportsControllerDailySalesPath = '/api/v1/reports/{restaurantId}/daily-sales';

  /**
   * Daily Sales Report.
   *
   * Every order placed on a single day (dateFrom, default today), with a delivered/cancelled/revenue summary. Restaurant OWNER/CO_OWNER/BRANCH_MANAGER or platform ADMIN only.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerDailySales()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerDailySales$Response(params: ReportsControllerDailySales$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerDailySales(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Daily Sales Report.
   *
   * Every order placed on a single day (dateFrom, default today), with a delivered/cancelled/revenue summary. Restaurant OWNER/CO_OWNER/BRANCH_MANAGER or platform ADMIN only.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerDailySales$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerDailySales(params: ReportsControllerDailySales$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerDailySales$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

  /** Path part for operation `reportsControllerOrders()` */
  static readonly ReportsControllerOrdersPath = '/api/v1/reports/{restaurantId}/orders';

  /**
   * Orders Report.
   *
   * Every order in the date range, optionally filtered by branch/status.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerOrders$Response(params: ReportsControllerOrders$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerOrders(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Orders Report.
   *
   * Every order in the date range, optionally filtered by branch/status.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerOrders(params: ReportsControllerOrders$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerOrders$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

  /** Path part for operation `reportsControllerRevenue()` */
  static readonly ReportsControllerRevenuePath = '/api/v1/reports/{restaurantId}/revenue';

  /**
   * Revenue Report.
   *
   * Delivered-order revenue, grouped by day, over the date range.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerRevenue()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerRevenue$Response(params: ReportsControllerRevenue$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerRevenue(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revenue Report.
   *
   * Delivered-order revenue, grouped by day, over the date range.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerRevenue$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerRevenue(params: ReportsControllerRevenue$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerRevenue$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

  /** Path part for operation `reportsControllerTaxSummary()` */
  static readonly ReportsControllerTaxSummaryPath = '/api/v1/reports/{restaurantId}/tax-summary';

  /**
   * Tax Summary.
   *
   * Tax collected on delivered orders, grouped by day, over the date range.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerTaxSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerTaxSummary$Response(params: ReportsControllerTaxSummary$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerTaxSummary(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Tax Summary.
   *
   * Tax collected on delivered orders, grouped by day, over the date range.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerTaxSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerTaxSummary(params: ReportsControllerTaxSummary$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerTaxSummary$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

  /** Path part for operation `reportsControllerPaymentSummary()` */
  static readonly ReportsControllerPaymentSummaryPath = '/api/v1/reports/{restaurantId}/payment-summary';

  /**
   * Payment Summary.
   *
   * Payment transactions grouped by method, over the date range.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerPaymentSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerPaymentSummary$Response(params: ReportsControllerPaymentSummary$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerPaymentSummary(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Payment Summary.
   *
   * Payment transactions grouped by method, over the date range.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerPaymentSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerPaymentSummary(params: ReportsControllerPaymentSummary$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerPaymentSummary$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

  /** Path part for operation `reportsControllerCancelledOrders()` */
  static readonly ReportsControllerCancelledOrdersPath = '/api/v1/reports/{restaurantId}/cancelled-orders';

  /**
   * Cancelled Orders Report.
   *
   * Every cancelled order in the date range.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerCancelledOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerCancelledOrders$Response(params: ReportsControllerCancelledOrders$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerCancelledOrders(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cancelled Orders Report.
   *
   * Every cancelled order in the date range.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerCancelledOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerCancelledOrders(params: ReportsControllerCancelledOrders$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerCancelledOrders$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

  /** Path part for operation `reportsControllerRefundSummary()` */
  static readonly ReportsControllerRefundSummaryPath = '/api/v1/reports/{restaurantId}/refund-summary';

  /**
   * Refund Summary.
   *
   * Every refund in the date range, across all payment methods.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportsControllerRefundSummary()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerRefundSummary$Response(params: ReportsControllerRefundSummary$Params, context?: HttpContext): Promise<StrictHttpResponse<ReportResponseDto>> {
    const obs = reportsControllerRefundSummary(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Refund Summary.
   *
   * Every refund in the date range, across all payment methods.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportsControllerRefundSummary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reportsControllerRefundSummary(params: ReportsControllerRefundSummary$Params, context?: HttpContext): Promise<ReportResponseDto> {
    const resp = this.reportsControllerRefundSummary$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReportResponseDto>): ReportResponseDto => r.body);
  }

}
