/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { PaginatedRestaurantsResponseDto } from '../models/paginated-restaurants-response-dto';
import { PaginatedRestaurantSummariesResponseDto } from '../models/paginated-restaurant-summaries-response-dto';
import { PaginatedReviewsResponseDto } from '../models/paginated-reviews-response-dto';
import { RestaurantResponseDto } from '../models/restaurant-response-dto';
import { restaurantsControllerApproveRestaurant } from '../fn/restaurants/restaurants-controller-approve-restaurant';
import { RestaurantsControllerApproveRestaurant$Params } from '../fn/restaurants/restaurants-controller-approve-restaurant';
import { restaurantsControllerCreateRestaurant } from '../fn/restaurants/restaurants-controller-create-restaurant';
import { RestaurantsControllerCreateRestaurant$Params } from '../fn/restaurants/restaurants-controller-create-restaurant';
import { restaurantsControllerFindAll } from '../fn/restaurants/restaurants-controller-find-all';
import { RestaurantsControllerFindAll$Params } from '../fn/restaurants/restaurants-controller-find-all';
import { restaurantsControllerGetAllForAdmin } from '../fn/restaurants/restaurants-controller-get-all-for-admin';
import { RestaurantsControllerGetAllForAdmin$Params } from '../fn/restaurants/restaurants-controller-get-all-for-admin';
import { restaurantsControllerGetMyRestaurants } from '../fn/restaurants/restaurants-controller-get-my-restaurants';
import { RestaurantsControllerGetMyRestaurants$Params } from '../fn/restaurants/restaurants-controller-get-my-restaurants';
import { restaurantsControllerGetRestaurantById } from '../fn/restaurants/restaurants-controller-get-restaurant-by-id';
import { RestaurantsControllerGetRestaurantById$Params } from '../fn/restaurants/restaurants-controller-get-restaurant-by-id';
import { restaurantsControllerRejectRestaurant } from '../fn/restaurants/restaurants-controller-reject-restaurant';
import { RestaurantsControllerRejectRestaurant$Params } from '../fn/restaurants/restaurants-controller-reject-restaurant';
import { restaurantsControllerRestoreRestaurant } from '../fn/restaurants/restaurants-controller-restore-restaurant';
import { RestaurantsControllerRestoreRestaurant$Params } from '../fn/restaurants/restaurants-controller-restore-restaurant';
import { restaurantsControllerSuspendRestaurant } from '../fn/restaurants/restaurants-controller-suspend-restaurant';
import { RestaurantsControllerSuspendRestaurant$Params } from '../fn/restaurants/restaurants-controller-suspend-restaurant';
import { restaurantsControllerUploadBanner } from '../fn/restaurants/restaurants-controller-upload-banner';
import { RestaurantsControllerUploadBanner$Params } from '../fn/restaurants/restaurants-controller-upload-banner';
import { restaurantsControllerUploadLogo } from '../fn/restaurants/restaurants-controller-upload-logo';
import { RestaurantsControllerUploadLogo$Params } from '../fn/restaurants/restaurants-controller-upload-logo';
import { ReviewResponseDto } from '../models/review-response-dto';
import { reviewsControllerCreateReview } from '../fn/restaurants/reviews-controller-create-review';
import { ReviewsControllerCreateReview$Params } from '../fn/restaurants/reviews-controller-create-review';
import { reviewsControllerDeleteReview } from '../fn/restaurants/reviews-controller-delete-review';
import { ReviewsControllerDeleteReview$Params } from '../fn/restaurants/reviews-controller-delete-review';
import { reviewsControllerGetMyReview } from '../fn/restaurants/reviews-controller-get-my-review';
import { ReviewsControllerGetMyReview$Params } from '../fn/restaurants/reviews-controller-get-my-review';
import { reviewsControllerGetReviews } from '../fn/restaurants/reviews-controller-get-reviews';
import { ReviewsControllerGetReviews$Params } from '../fn/restaurants/reviews-controller-get-reviews';

@Injectable({ providedIn: 'root' })
export class RestaurantsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `restaurantsControllerFindAll()` */
  static readonly RestaurantsControllerFindAllPath = '/api/v1/restaurants';

  /**
   * Get restaurants.
   *
   * Returns a paginated list of restaurants available to customers.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerFindAll$Response(params?: RestaurantsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedRestaurantSummariesResponseDto>> {
    const obs = restaurantsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurants.
   *
   * Returns a paginated list of restaurants available to customers.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerFindAll(params?: RestaurantsControllerFindAll$Params, context?: HttpContext): Promise<PaginatedRestaurantSummariesResponseDto> {
    const resp = this.restaurantsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedRestaurantSummariesResponseDto>): PaginatedRestaurantSummariesResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerCreateRestaurant()` */
  static readonly RestaurantsControllerCreateRestaurantPath = '/api/v1/restaurants';

  /**
   * Create restaurant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerCreateRestaurant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  restaurantsControllerCreateRestaurant$Response(params: RestaurantsControllerCreateRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerCreateRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create restaurant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerCreateRestaurant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  restaurantsControllerCreateRestaurant(params: RestaurantsControllerCreateRestaurant$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerCreateRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerGetMyRestaurants()` */
  static readonly RestaurantsControllerGetMyRestaurantsPath = '/api/v1/restaurants/me';

  /**
   * Get restaurants owned by current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerGetMyRestaurants()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetMyRestaurants$Response(params?: RestaurantsControllerGetMyRestaurants$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RestaurantResponseDto>>> {
    const obs = restaurantsControllerGetMyRestaurants(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurants owned by current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerGetMyRestaurants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetMyRestaurants(params?: RestaurantsControllerGetMyRestaurants$Params, context?: HttpContext): Promise<Array<RestaurantResponseDto>> {
    const resp = this.restaurantsControllerGetMyRestaurants$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RestaurantResponseDto>>): Array<RestaurantResponseDto> => r.body);
  }

  /** Path part for operation `restaurantsControllerGetAllForAdmin()` */
  static readonly RestaurantsControllerGetAllForAdminPath = '/api/v1/restaurants/admin';

  /**
   * Get restaurants (admin).
   *
   * Returns a paginated, filterable, platform-wide list of restaurants of any status, including owner information. Distinct from the public listing, which only ever returns approved, active restaurants and never includes owner details.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerGetAllForAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetAllForAdmin$Response(params?: RestaurantsControllerGetAllForAdmin$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedRestaurantsResponseDto>> {
    const obs = restaurantsControllerGetAllForAdmin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurants (admin).
   *
   * Returns a paginated, filterable, platform-wide list of restaurants of any status, including owner information. Distinct from the public listing, which only ever returns approved, active restaurants and never includes owner details.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerGetAllForAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetAllForAdmin(params?: RestaurantsControllerGetAllForAdmin$Params, context?: HttpContext): Promise<PaginatedRestaurantsResponseDto> {
    const resp = this.restaurantsControllerGetAllForAdmin$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedRestaurantsResponseDto>): PaginatedRestaurantsResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerApproveRestaurant()` */
  static readonly RestaurantsControllerApproveRestaurantPath = '/api/v1/restaurants/{id}/approve';

  /**
   * Approve restaurant.
   *
   * Approves a pending restaurant application.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerApproveRestaurant()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerApproveRestaurant$Response(params: RestaurantsControllerApproveRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerApproveRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Approve restaurant.
   *
   * Approves a pending restaurant application.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerApproveRestaurant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerApproveRestaurant(params: RestaurantsControllerApproveRestaurant$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerApproveRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerRejectRestaurant()` */
  static readonly RestaurantsControllerRejectRestaurantPath = '/api/v1/restaurants/{id}/reject';

  /**
   * Reject restaurant.
   *
   * Rejects a pending restaurant application.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerRejectRestaurant()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerRejectRestaurant$Response(params: RestaurantsControllerRejectRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerRejectRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Reject restaurant.
   *
   * Rejects a pending restaurant application.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerRejectRestaurant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerRejectRestaurant(params: RestaurantsControllerRejectRestaurant$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerRejectRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerSuspendRestaurant()` */
  static readonly RestaurantsControllerSuspendRestaurantPath = '/api/v1/restaurants/{id}/suspend';

  /**
   * Suspend restaurant.
   *
   * Suspends an approved restaurant.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerSuspendRestaurant()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerSuspendRestaurant$Response(params: RestaurantsControllerSuspendRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerSuspendRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Suspend restaurant.
   *
   * Suspends an approved restaurant.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerSuspendRestaurant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerSuspendRestaurant(params: RestaurantsControllerSuspendRestaurant$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerSuspendRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerRestoreRestaurant()` */
  static readonly RestaurantsControllerRestoreRestaurantPath = '/api/v1/restaurants/{id}/restore';

  /**
   * Restore restaurant.
   *
   * Restores a suspended restaurant back to approved.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerRestoreRestaurant()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerRestoreRestaurant$Response(params: RestaurantsControllerRestoreRestaurant$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerRestoreRestaurant(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Restore restaurant.
   *
   * Restores a suspended restaurant back to approved.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerRestoreRestaurant$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerRestoreRestaurant(params: RestaurantsControllerRestoreRestaurant$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerRestoreRestaurant$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerGetRestaurantById()` */
  static readonly RestaurantsControllerGetRestaurantByIdPath = '/api/v1/restaurants/{id}';

  /**
   * Get restaurant by ID.
   *
   * Public — no authentication required, so anonymous customers can browse restaurant detail pages.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerGetRestaurantById()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetRestaurantById$Response(params: RestaurantsControllerGetRestaurantById$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerGetRestaurantById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get restaurant by ID.
   *
   * Public — no authentication required, so anonymous customers can browse restaurant detail pages.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerGetRestaurantById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  restaurantsControllerGetRestaurantById(params: RestaurantsControllerGetRestaurantById$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerGetRestaurantById$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerUploadLogo()` */
  static readonly RestaurantsControllerUploadLogoPath = '/api/v1/restaurants/{id}/logo';

  /**
   * Upload restaurant logo.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerUploadLogo()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  restaurantsControllerUploadLogo$Response(params: RestaurantsControllerUploadLogo$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerUploadLogo(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Upload restaurant logo.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerUploadLogo$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  restaurantsControllerUploadLogo(params: RestaurantsControllerUploadLogo$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerUploadLogo$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `restaurantsControllerUploadBanner()` */
  static readonly RestaurantsControllerUploadBannerPath = '/api/v1/restaurants/{id}/banner';

  /**
   * Upload restaurant banner.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `restaurantsControllerUploadBanner()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  restaurantsControllerUploadBanner$Response(params: RestaurantsControllerUploadBanner$Params, context?: HttpContext): Promise<StrictHttpResponse<RestaurantResponseDto>> {
    const obs = restaurantsControllerUploadBanner(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Upload restaurant banner.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `restaurantsControllerUploadBanner$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  restaurantsControllerUploadBanner(params: RestaurantsControllerUploadBanner$Params, context?: HttpContext): Promise<RestaurantResponseDto> {
    const resp = this.restaurantsControllerUploadBanner$Response(params, context);
    return resp.then((r: StrictHttpResponse<RestaurantResponseDto>): RestaurantResponseDto => r.body);
  }

  /** Path part for operation `reviewsControllerGetReviews()` */
  static readonly ReviewsControllerGetReviewsPath = '/api/v1/restaurants/{id}/reviews';

  /**
   * List reviews for a restaurant.
   *
   * Public — paginated, newest first.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reviewsControllerGetReviews()` instead.
   *
   * This method doesn't expect any request body.
   */
  reviewsControllerGetReviews$Response(params: ReviewsControllerGetReviews$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedReviewsResponseDto>> {
    const obs = reviewsControllerGetReviews(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List reviews for a restaurant.
   *
   * Public — paginated, newest first.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reviewsControllerGetReviews$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reviewsControllerGetReviews(params: ReviewsControllerGetReviews$Params, context?: HttpContext): Promise<PaginatedReviewsResponseDto> {
    const resp = this.reviewsControllerGetReviews$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedReviewsResponseDto>): PaginatedReviewsResponseDto => r.body);
  }

  /** Path part for operation `reviewsControllerCreateReview()` */
  static readonly ReviewsControllerCreateReviewPath = '/api/v1/restaurants/{id}/reviews';

  /**
   * Rate a restaurant.
   *
   * Submits (or updates) the current customer's rating and review for a restaurant, and recomputes the restaurant's aggregated rating. Requires at least one DELIVERED order from this restaurant.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reviewsControllerCreateReview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reviewsControllerCreateReview$Response(params: ReviewsControllerCreateReview$Params, context?: HttpContext): Promise<StrictHttpResponse<ReviewResponseDto>> {
    const obs = reviewsControllerCreateReview(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rate a restaurant.
   *
   * Submits (or updates) the current customer's rating and review for a restaurant, and recomputes the restaurant's aggregated rating. Requires at least one DELIVERED order from this restaurant.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reviewsControllerCreateReview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reviewsControllerCreateReview(params: ReviewsControllerCreateReview$Params, context?: HttpContext): Promise<ReviewResponseDto> {
    const resp = this.reviewsControllerCreateReview$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReviewResponseDto>): ReviewResponseDto => r.body);
  }

  /** Path part for operation `reviewsControllerDeleteReview()` */
  static readonly ReviewsControllerDeleteReviewPath = '/api/v1/restaurants/{id}/reviews';

  /**
   * Delete my review for a restaurant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reviewsControllerDeleteReview()` instead.
   *
   * This method doesn't expect any request body.
   */
  reviewsControllerDeleteReview$Response(params: ReviewsControllerDeleteReview$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = reviewsControllerDeleteReview(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete my review for a restaurant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reviewsControllerDeleteReview$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reviewsControllerDeleteReview(params: ReviewsControllerDeleteReview$Params, context?: HttpContext): Promise<void> {
    const resp = this.reviewsControllerDeleteReview$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `reviewsControllerGetMyReview()` */
  static readonly ReviewsControllerGetMyReviewPath = '/api/v1/restaurants/{id}/reviews/me';

  /**
   * Get my review for a restaurant.
   *
   * Returns null if the current customer has not reviewed this restaurant.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reviewsControllerGetMyReview()` instead.
   *
   * This method doesn't expect any request body.
   */
  reviewsControllerGetMyReview$Response(params: ReviewsControllerGetMyReview$Params, context?: HttpContext): Promise<StrictHttpResponse<ReviewResponseDto>> {
    const obs = reviewsControllerGetMyReview(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get my review for a restaurant.
   *
   * Returns null if the current customer has not reviewed this restaurant.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reviewsControllerGetMyReview$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reviewsControllerGetMyReview(params: ReviewsControllerGetMyReview$Params, context?: HttpContext): Promise<ReviewResponseDto> {
    const resp = this.reviewsControllerGetMyReview$Response(params, context);
    return resp.then((r: StrictHttpResponse<ReviewResponseDto>): ReviewResponseDto => r.body);
  }

}
