/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GlobalSearchResponseDto } from '../models/global-search-response-dto';
import { PaginatedMenuItemSearchResponseDto } from '../models/paginated-menu-item-search-response-dto';
import { RecentSearchDto } from '../models/recent-search-dto';
import { searchControllerClearRecent } from '../fn/search/search-controller-clear-recent';
import { SearchControllerClearRecent$Params } from '../fn/search/search-controller-clear-recent';
import { searchControllerDeleteRecent } from '../fn/search/search-controller-delete-recent';
import { SearchControllerDeleteRecent$Params } from '../fn/search/search-controller-delete-recent';
import { searchControllerGetRecent } from '../fn/search/search-controller-get-recent';
import { SearchControllerGetRecent$Params } from '../fn/search/search-controller-get-recent';
import { searchControllerGetSuggestions } from '../fn/search/search-controller-get-suggestions';
import { SearchControllerGetSuggestions$Params } from '../fn/search/search-controller-get-suggestions';
import { searchControllerGetTrending } from '../fn/search/search-controller-get-trending';
import { SearchControllerGetTrending$Params } from '../fn/search/search-controller-get-trending';
import { searchControllerGlobalSearch } from '../fn/search/search-controller-global-search';
import { SearchControllerGlobalSearch$Params } from '../fn/search/search-controller-global-search';
import { searchControllerLogSearch } from '../fn/search/search-controller-log-search';
import { SearchControllerLogSearch$Params } from '../fn/search/search-controller-log-search';
import { searchControllerRecordRecent } from '../fn/search/search-controller-record-recent';
import { SearchControllerRecordRecent$Params } from '../fn/search/search-controller-record-recent';
import { searchControllerSearchMenuItems } from '../fn/search/search-controller-search-menu-items';
import { SearchControllerSearchMenuItems$Params } from '../fn/search/search-controller-search-menu-items';
import { SearchSuggestionDto } from '../models/search-suggestion-dto';
import { TrendingSearchDto } from '../models/trending-search-dto';

@Injectable({ providedIn: 'root' })
export class SearchService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchControllerGlobalSearch()` */
  static readonly SearchControllerGlobalSearchPath = '/api/v1/search/global';

  /**
   * Global search.
   *
   * Quick combined preview across restaurants and menu items (cross-restaurant) for a search bar. Not deeply paginated — use GET /restaurants?search= or GET /search/menu-items for the full paginated view of each.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerGlobalSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGlobalSearch$Response(params: SearchControllerGlobalSearch$Params, context?: HttpContext): Promise<StrictHttpResponse<GlobalSearchResponseDto>> {
    const obs = searchControllerGlobalSearch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Global search.
   *
   * Quick combined preview across restaurants and menu items (cross-restaurant) for a search bar. Not deeply paginated — use GET /restaurants?search= or GET /search/menu-items for the full paginated view of each.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerGlobalSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGlobalSearch(params: SearchControllerGlobalSearch$Params, context?: HttpContext): Promise<GlobalSearchResponseDto> {
    const resp = this.searchControllerGlobalSearch$Response(params, context);
    return resp.then((r: StrictHttpResponse<GlobalSearchResponseDto>): GlobalSearchResponseDto => r.body);
  }

  /** Path part for operation `searchControllerSearchMenuItems()` */
  static readonly SearchControllerSearchMenuItemsPath = '/api/v1/search/menu-items';

  /**
   * Cross-restaurant menu item search.
   *
   * Paginated search for dishes across every approved, active restaurant.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerSearchMenuItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerSearchMenuItems$Response(params: SearchControllerSearchMenuItems$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedMenuItemSearchResponseDto>> {
    const obs = searchControllerSearchMenuItems(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Cross-restaurant menu item search.
   *
   * Paginated search for dishes across every approved, active restaurant.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerSearchMenuItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerSearchMenuItems(params: SearchControllerSearchMenuItems$Params, context?: HttpContext): Promise<PaginatedMenuItemSearchResponseDto> {
    const resp = this.searchControllerSearchMenuItems$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedMenuItemSearchResponseDto>): PaginatedMenuItemSearchResponseDto => r.body);
  }

  /** Path part for operation `searchControllerGetSuggestions()` */
  static readonly SearchControllerGetSuggestionsPath = '/api/v1/search/suggestions';

  /**
   * Live search suggestions.
   *
   * Small, fast, mixed set of restaurant/cuisine/menu-item name matches for autocomplete-as-you-type.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerGetSuggestions()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGetSuggestions$Response(params: SearchControllerGetSuggestions$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<SearchSuggestionDto>>> {
    const obs = searchControllerGetSuggestions(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Live search suggestions.
   *
   * Small, fast, mixed set of restaurant/cuisine/menu-item name matches for autocomplete-as-you-type.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerGetSuggestions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGetSuggestions(params: SearchControllerGetSuggestions$Params, context?: HttpContext): Promise<Array<SearchSuggestionDto>> {
    const resp = this.searchControllerGetSuggestions$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<SearchSuggestionDto>>): Array<SearchSuggestionDto> => r.body);
  }

  /** Path part for operation `searchControllerGetTrending()` */
  static readonly SearchControllerGetTrendingPath = '/api/v1/search/trending';

  /**
   * Trending searches.
   *
   * Precomputed by a scheduled BullMQ aggregation job over recent search volume — never aggregated on the request path.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerGetTrending()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGetTrending$Response(params?: SearchControllerGetTrending$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TrendingSearchDto>>> {
    const obs = searchControllerGetTrending(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Trending searches.
   *
   * Precomputed by a scheduled BullMQ aggregation job over recent search volume — never aggregated on the request path.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerGetTrending$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGetTrending(params?: SearchControllerGetTrending$Params, context?: HttpContext): Promise<Array<TrendingSearchDto>> {
    const resp = this.searchControllerGetTrending$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TrendingSearchDto>>): Array<TrendingSearchDto> => r.body);
  }

  /** Path part for operation `searchControllerLogSearch()` */
  static readonly SearchControllerLogSearchPath = '/api/v1/search/log';

  /**
   * Log a committed search.
   *
   * Public — records the query for trending-search aggregation. Call this whenever a user commits a search (e.g. presses enter / opens results), not on every keystroke.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerLogSearch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchControllerLogSearch$Response(params: SearchControllerLogSearch$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = searchControllerLogSearch(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Log a committed search.
   *
   * Public — records the query for trending-search aggregation. Call this whenever a user commits a search (e.g. presses enter / opens results), not on every keystroke.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerLogSearch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchControllerLogSearch(params: SearchControllerLogSearch$Params, context?: HttpContext): Promise<void> {
    const resp = this.searchControllerLogSearch$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `searchControllerGetRecent()` */
  static readonly SearchControllerGetRecentPath = '/api/v1/search/recent';

  /**
   * Get the authenticated customer's recent searches.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerGetRecent()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGetRecent$Response(params?: SearchControllerGetRecent$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RecentSearchDto>>> {
    const obs = searchControllerGetRecent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get the authenticated customer's recent searches.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerGetRecent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerGetRecent(params?: SearchControllerGetRecent$Params, context?: HttpContext): Promise<Array<RecentSearchDto>> {
    const resp = this.searchControllerGetRecent$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RecentSearchDto>>): Array<RecentSearchDto> => r.body);
  }

  /** Path part for operation `searchControllerRecordRecent()` */
  static readonly SearchControllerRecordRecentPath = '/api/v1/search/recent';

  /**
   * Record a recent search for the authenticated customer.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerRecordRecent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchControllerRecordRecent$Response(params: SearchControllerRecordRecent$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = searchControllerRecordRecent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Record a recent search for the authenticated customer.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerRecordRecent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  searchControllerRecordRecent(params: SearchControllerRecordRecent$Params, context?: HttpContext): Promise<void> {
    const resp = this.searchControllerRecordRecent$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `searchControllerClearRecent()` */
  static readonly SearchControllerClearRecentPath = '/api/v1/search/recent';

  /**
   * Clear all recent searches for the authenticated customer.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerClearRecent()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerClearRecent$Response(params?: SearchControllerClearRecent$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = searchControllerClearRecent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Clear all recent searches for the authenticated customer.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerClearRecent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerClearRecent(params?: SearchControllerClearRecent$Params, context?: HttpContext): Promise<void> {
    const resp = this.searchControllerClearRecent$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `searchControllerDeleteRecent()` */
  static readonly SearchControllerDeleteRecentPath = '/api/v1/search/recent/{id}';

  /**
   * Delete a single recent search entry.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchControllerDeleteRecent()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerDeleteRecent$Response(params: SearchControllerDeleteRecent$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = searchControllerDeleteRecent(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete a single recent search entry.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchControllerDeleteRecent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchControllerDeleteRecent(params: SearchControllerDeleteRecent$Params, context?: HttpContext): Promise<void> {
    const resp = this.searchControllerDeleteRecent$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
