/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { systemControllerPresenceTest } from '../fn/system/system-controller-presence-test';
import { SystemControllerPresenceTest$Params } from '../fn/system/system-controller-presence-test';
import { systemControllerQueueHealth } from '../fn/system/system-controller-queue-health';
import { SystemControllerQueueHealth$Params } from '../fn/system/system-controller-queue-health';
import { systemControllerQueueTest } from '../fn/system/system-controller-queue-test';
import { SystemControllerQueueTest$Params } from '../fn/system/system-controller-queue-test';
import { systemControllerTestRedis } from '../fn/system/system-controller-test-redis';
import { SystemControllerTestRedis$Params } from '../fn/system/system-controller-test-redis';

@Injectable({ providedIn: 'root' })
export class SystemService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `systemControllerTestRedis()` */
  static readonly SystemControllerTestRedisPath = '/api/v1/system/redis-test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `systemControllerTestRedis()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerTestRedis$Response(params?: SystemControllerTestRedis$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = systemControllerTestRedis(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `systemControllerTestRedis$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerTestRedis(params?: SystemControllerTestRedis$Params, context?: HttpContext): Promise<void> {
    const resp = this.systemControllerTestRedis$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `systemControllerQueueTest()` */
  static readonly SystemControllerQueueTestPath = '/api/v1/system/queue-test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `systemControllerQueueTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerQueueTest$Response(params?: SystemControllerQueueTest$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = systemControllerQueueTest(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `systemControllerQueueTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerQueueTest(params?: SystemControllerQueueTest$Params, context?: HttpContext): Promise<void> {
    const resp = this.systemControllerQueueTest$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `systemControllerQueueHealth()` */
  static readonly SystemControllerQueueHealthPath = '/api/v1/system/queue-health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `systemControllerQueueHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerQueueHealth$Response(params?: SystemControllerQueueHealth$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = systemControllerQueueHealth(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `systemControllerQueueHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerQueueHealth(params?: SystemControllerQueueHealth$Params, context?: HttpContext): Promise<void> {
    const resp = this.systemControllerQueueHealth$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `systemControllerPresenceTest()` */
  static readonly SystemControllerPresenceTestPath = '/api/v1/system/presence-test/{partnerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `systemControllerPresenceTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerPresenceTest$Response(params: SystemControllerPresenceTest$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = systemControllerPresenceTest(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `systemControllerPresenceTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  systemControllerPresenceTest(params: SystemControllerPresenceTest$Params, context?: HttpContext): Promise<void> {
    const resp = this.systemControllerPresenceTest$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
