/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OrderLocationResponseDto } from '../models/order-location-response-dto';
import { trackingControllerGetOrderLocation } from '../fn/tracking/tracking-controller-get-order-location';
import { TrackingControllerGetOrderLocation$Params } from '../fn/tracking/tracking-controller-get-order-location';
import { trackingControllerUpdateLocation } from '../fn/tracking/tracking-controller-update-location';
import { TrackingControllerUpdateLocation$Params } from '../fn/tracking/tracking-controller-update-location';

@Injectable({ providedIn: 'root' })
export class TrackingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `trackingControllerUpdateLocation()` */
  static readonly TrackingControllerUpdateLocationPath = '/api/v1/tracking/location';

  /**
   * Update delivery location.
   *
   * Update live GPS location for an order delivery. Restricted to the order's assigned delivery partner (or an admin).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `trackingControllerUpdateLocation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  trackingControllerUpdateLocation$Response(params: TrackingControllerUpdateLocation$Params, context?: HttpContext): Promise<StrictHttpResponse<OrderLocationResponseDto>> {
    const obs = trackingControllerUpdateLocation(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update delivery location.
   *
   * Update live GPS location for an order delivery. Restricted to the order's assigned delivery partner (or an admin).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `trackingControllerUpdateLocation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  trackingControllerUpdateLocation(params: TrackingControllerUpdateLocation$Params, context?: HttpContext): Promise<OrderLocationResponseDto> {
    const resp = this.trackingControllerUpdateLocation$Response(params, context);
    return resp.then((r: StrictHttpResponse<OrderLocationResponseDto>): OrderLocationResponseDto => r.body);
  }

  /** Path part for operation `trackingControllerGetOrderLocation()` */
  static readonly TrackingControllerGetOrderLocationPath = '/api/v1/tracking/order/{orderId}';

  /**
   * Get current order location.
   *
   * Retrieve the latest tracked location and ETA for an order. Restricted to the order's customer, assigned delivery partner, restaurant owner/manager, or an admin.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `trackingControllerGetOrderLocation()` instead.
   *
   * This method doesn't expect any request body.
   */
  trackingControllerGetOrderLocation$Response(params: TrackingControllerGetOrderLocation$Params, context?: HttpContext): Promise<StrictHttpResponse<OrderLocationResponseDto>> {
    const obs = trackingControllerGetOrderLocation(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get current order location.
   *
   * Retrieve the latest tracked location and ETA for an order. Restricted to the order's customer, assigned delivery partner, restaurant owner/manager, or an admin.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `trackingControllerGetOrderLocation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  trackingControllerGetOrderLocation(params: TrackingControllerGetOrderLocation$Params, context?: HttpContext): Promise<OrderLocationResponseDto> {
    const resp = this.trackingControllerGetOrderLocation$Response(params, context);
    return resp.then((r: StrictHttpResponse<OrderLocationResponseDto>): OrderLocationResponseDto => r.body);
  }

}
