/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { UserResponseDto } from '../models/user-response-dto';
import { usersControllerGetAllUsers } from '../fn/users/users-controller-get-all-users';
import { UsersControllerGetAllUsers$Params } from '../fn/users/users-controller-get-all-users';
import { usersControllerGetProfile } from '../fn/users/users-controller-get-profile';
import { UsersControllerGetProfile$Params } from '../fn/users/users-controller-get-profile';
import { usersControllerUpdateProfile } from '../fn/users/users-controller-update-profile';
import { UsersControllerUpdateProfile$Params } from '../fn/users/users-controller-update-profile';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usersControllerGetProfile()` */
  static readonly UsersControllerGetProfilePath = '/api/v1/users/me';

  /**
   * Get current user profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerGetProfile()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerGetProfile$Response(params?: UsersControllerGetProfile$Params, context?: HttpContext): Promise<StrictHttpResponse<UserResponseDto>> {
    const obs = usersControllerGetProfile(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get current user profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerGetProfile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerGetProfile(params?: UsersControllerGetProfile$Params, context?: HttpContext): Promise<UserResponseDto> {
    const resp = this.usersControllerGetProfile$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body);
  }

  /** Path part for operation `usersControllerUpdateProfile()` */
  static readonly UsersControllerUpdateProfilePath = '/api/v1/users/me';

  /**
   * Update current user profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerUpdateProfile()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerUpdateProfile$Response(params: UsersControllerUpdateProfile$Params, context?: HttpContext): Promise<StrictHttpResponse<UserResponseDto>> {
    const obs = usersControllerUpdateProfile(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update current user profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerUpdateProfile$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerUpdateProfile(params: UsersControllerUpdateProfile$Params, context?: HttpContext): Promise<UserResponseDto> {
    const resp = this.usersControllerUpdateProfile$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserResponseDto>): UserResponseDto => r.body);
  }

  /** Path part for operation `usersControllerGetAllUsers()` */
  static readonly UsersControllerGetAllUsersPath = '/api/v1/users';

  /**
   * Get all users.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerGetAllUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerGetAllUsers$Response(params?: UsersControllerGetAllUsers$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UserResponseDto>>> {
    const obs = usersControllerGetAllUsers(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get all users.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerGetAllUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerGetAllUsers(params?: UsersControllerGetAllUsers$Params, context?: HttpContext): Promise<Array<UserResponseDto>> {
    const resp = this.usersControllerGetAllUsers$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UserResponseDto>>): Array<UserResponseDto> => r.body);
  }

}
