/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminTicketResponseDto } from '../../models/admin-ticket-response-dto';
import { AssignTicketDto } from '../../models/assign-ticket-dto';

export interface TicketsControllerAssignTicket$Params {
  id: string;
      body: AssignTicketDto
}

export function ticketsControllerAssignTicket(http: HttpClient, rootUrl: string, params: TicketsControllerAssignTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminTicketResponseDto>> {
  const rb = new RequestBuilder(rootUrl, ticketsControllerAssignTicket.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminTicketResponseDto>;
    })
  );
}

ticketsControllerAssignTicket.PATH = '/api/v1/tickets/admin/{id}/assign';
