/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProofOtpGeneratedResponseDto } from '../../models/proof-otp-generated-response-dto';

export interface ProofControllerGenerateDeliveryOtp$Params {
  orderId: string;
}

export function proofControllerGenerateDeliveryOtp(http: HttpClient, rootUrl: string, params: ProofControllerGenerateDeliveryOtp$Params, context?: HttpContext): Observable<StrictHttpResponse<ProofOtpGeneratedResponseDto>> {
  const rb = new RequestBuilder(rootUrl, proofControllerGenerateDeliveryOtp.PATH, 'post');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProofOtpGeneratedResponseDto>;
    })
  );
}

proofControllerGenerateDeliveryOtp.PATH = '/api/v1/delivery/orders/{orderId}/proof/delivery/generate';
