/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RestaurantArrivalResponseDto } from '../../models/restaurant-arrival-response-dto';

export interface ProofControllerGetArrivalStatus$Params {
  orderId: string;
}

export function proofControllerGetArrivalStatus(http: HttpClient, rootUrl: string, params: ProofControllerGetArrivalStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<RestaurantArrivalResponseDto>> {
  const rb = new RequestBuilder(rootUrl, proofControllerGetArrivalStatus.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RestaurantArrivalResponseDto>;
    })
  );
}

proofControllerGetArrivalStatus.PATH = '/api/v1/delivery/orders/{orderId}/proof/pickup/arrival';
