/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProofOtpStatusResponseDto } from '../../models/proof-otp-status-response-dto';

export interface ProofControllerGetDeliveryStatus$Params {
  orderId: string;
}

export function proofControllerGetDeliveryStatus(http: HttpClient, rootUrl: string, params: ProofControllerGetDeliveryStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ProofOtpStatusResponseDto>> {
  const rb = new RequestBuilder(rootUrl, proofControllerGetDeliveryStatus.PATH, 'get');
  if (params) {
    rb.path('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProofOtpStatusResponseDto>;
    })
  );
}

proofControllerGetDeliveryStatus.PATH = '/api/v1/delivery/orders/{orderId}/proof/delivery/status';
