/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedAdminNotificationsResponseDto } from '../../models/paginated-admin-notifications-response-dto';

export interface NotificationsControllerGetAllForAdmin$Params {
  dateTo?: any;
  dateFrom?: any;

/**
 * Matches recipient first name, last name, email, or phone
 */
  recipient?: any;
  status?: 'PENDING' | 'SENT' | 'FAILED' | 'READ';
  channel?: 'PUSH' | 'EMAIL' | 'SMS' | 'WHATSAPP' | 'IN_APP';
  type?: 'ORDER_PLACED' | 'ORDER_STATUS_CHANGED' | 'DELIVERY_PARTNER_ASSIGNED' | 'OFFER' | 'WALLET_CREDIT' | 'REFERRAL_REWARD' | 'TICKET_STATUS_CHANGED' | 'TICKET_MESSAGE' | 'GENERAL' | 'NEW_ORDER_FOR_RESTAURANT' | 'ORDER_CANCELLED_FOR_RESTAURANT' | 'REFUND_FOR_RESTAURANT' | 'CUSTOMER_MESSAGE_FOR_RESTAURANT' | 'DELIVERY_PARTNER_VERIFICATION_SUBMITTED' | 'DELIVERY_PARTNER_VERIFICATION_APPROVED' | 'DELIVERY_PARTNER_VERIFICATION_REJECTED' | 'DELIVERY_PARTNER_CHANGES_REQUESTED' | 'DELIVERY_PARTNER_DOCUMENT_EXPIRING';

/**
 * Matches subject/body text
 */
  search?: any;
  limit?: number;
  page?: number;
}

export function notificationsControllerGetAllForAdmin(http: HttpClient, rootUrl: string, params?: NotificationsControllerGetAllForAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAdminNotificationsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerGetAllForAdmin.PATH, 'get');
  if (params) {
    rb.query('dateTo', params.dateTo, {});
    rb.query('dateFrom', params.dateFrom, {});
    rb.query('recipient', params.recipient, {});
    rb.query('status', params.status, {});
    rb.query('channel', params.channel, {});
    rb.query('type', params.type, {});
    rb.query('search', params.search, {});
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedAdminNotificationsResponseDto>;
    })
  );
}

notificationsControllerGetAllForAdmin.PATH = '/api/v1/notifications/admin';
