/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MarkAllReadResponseDto } from '../../models/mark-all-read-response-dto';

export interface NotificationsControllerMarkAllMyNotificationsAsRead$Params {
}

export function notificationsControllerMarkAllMyNotificationsAsRead(http: HttpClient, rootUrl: string, params?: NotificationsControllerMarkAllMyNotificationsAsRead$Params, context?: HttpContext): Observable<StrictHttpResponse<MarkAllReadResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerMarkAllMyNotificationsAsRead.PATH, 'patch');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MarkAllReadResponseDto>;
    })
  );
}

notificationsControllerMarkAllMyNotificationsAsRead.PATH = '/api/v1/notifications/me/read-all';
