/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminNotificationResponseDto } from '../../models/admin-notification-response-dto';

export interface NotificationsControllerRetryNotification$Params {

/**
 * Notification ID
 */
  id: string;
}

export function notificationsControllerRetryNotification(http: HttpClient, rootUrl: string, params: NotificationsControllerRetryNotification$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminNotificationResponseDto>> {
  const rb = new RequestBuilder(rootUrl, notificationsControllerRetryNotification.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminNotificationResponseDto>;
    })
  );
}

notificationsControllerRetryNotification.PATH = '/api/v1/notifications/admin/{id}/retry';
