/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MediaResponseDto } from '../../models/media-response-dto';
import { ReorderMediaDto } from '../../models/reorder-media-dto';

export interface MediaControllerReorder$Params {
  restaurantId: string;
      body: ReorderMediaDto
}

export function mediaControllerReorder(http: HttpClient, rootUrl: string, params: MediaControllerReorder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MediaResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, mediaControllerReorder.PATH, 'patch');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MediaResponseDto>>;
    })
  );
}

mediaControllerReorder.PATH = '/api/v1/restaurants/{restaurantId}/media/reorder';
