/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MediaResponseDto } from '../../models/media-response-dto';

export interface MediaControllerFindAll$Params {
  restaurantId: string;
}

export function mediaControllerFindAll(http: HttpClient, rootUrl: string, params: MediaControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MediaResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, mediaControllerFindAll.PATH, 'get');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MediaResponseDto>>;
    })
  );
}

mediaControllerFindAll.PATH = '/api/v1/restaurants/{restaurantId}/media';
