/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnboardingResponseDto } from '../../models/onboarding-response-dto';
import { SubmitOnboardingDto } from '../../models/submit-onboarding-dto';

export interface OnboardingControllerSubmit$Params {
  restaurantId: string;
      body: SubmitOnboardingDto
}

export function onboardingControllerSubmit(http: HttpClient, rootUrl: string, params: OnboardingControllerSubmit$Params, context?: HttpContext): Observable<StrictHttpResponse<OnboardingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, onboardingControllerSubmit.PATH, 'post');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnboardingResponseDto>;
    })
  );
}

onboardingControllerSubmit.PATH = '/api/v1/restaurants/{restaurantId}/onboarding/submit';
