/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OnboardingResponseDto } from '../../models/onboarding-response-dto';

export interface OnboardingControllerCompleteStep$Params {
  restaurantId: string;

/**
 * 1-12
 */
  step: number;
}

export function onboardingControllerCompleteStep(http: HttpClient, rootUrl: string, params: OnboardingControllerCompleteStep$Params, context?: HttpContext): Observable<StrictHttpResponse<OnboardingResponseDto>> {
  const rb = new RequestBuilder(rootUrl, onboardingControllerCompleteStep.PATH, 'patch');
  if (params) {
    rb.path('restaurantId', params.restaurantId, {});
    rb.path('step', params.step, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OnboardingResponseDto>;
    })
  );
}

onboardingControllerCompleteStep.PATH = '/api/v1/restaurants/{restaurantId}/onboarding/steps/{step}';
