/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedAdminPaymentsResponseDto } from '../../models/paginated-admin-payments-response-dto';

export interface PaymentsControllerGetAllForAdmin$Params {
  dateTo?: any;
  dateFrom?: any;
  method?: 'UPI' | 'CARD' | 'NETBANKING' | 'WALLET';
  provider?: 'RAZORPAY' | 'STRIPE';
  status?: 'PENDING' | 'SUCCESS' | 'FAILED' | 'REFUNDED';

/**
 * Matches order number or customer name/email/phone
 */
  search?: any;
  limit?: number;
  page?: number;
}

export function paymentsControllerGetAllForAdmin(http: HttpClient, rootUrl: string, params?: PaymentsControllerGetAllForAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedAdminPaymentsResponseDto>> {
  const rb = new RequestBuilder(rootUrl, paymentsControllerGetAllForAdmin.PATH, 'get');
  if (params) {
    rb.query('dateTo', params.dateTo, {});
    rb.query('dateFrom', params.dateFrom, {});
    rb.query('method', params.method, {});
    rb.query('provider', params.provider, {});
    rb.query('status', params.status, {});
    rb.query('search', params.search, {});
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedAdminPaymentsResponseDto>;
    })
  );
}

paymentsControllerGetAllForAdmin.PATH = '/api/v1/payments/admin';
