/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePaymentDto } from '../../models/create-payment-dto';
import { CreatePaymentResponseDto } from '../../models/create-payment-response-dto';

export interface PaymentsControllerCreatePayment$Params {
      body: CreatePaymentDto
}

export function paymentsControllerCreatePayment(http: HttpClient, rootUrl: string, params: PaymentsControllerCreatePayment$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatePaymentResponseDto>> {
  const rb = new RequestBuilder(rootUrl, paymentsControllerCreatePayment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatePaymentResponseDto>;
    })
  );
}

paymentsControllerCreatePayment.PATH = '/api/v1/payments/create';
